- README.md
- docs/README.md
- helm/volsync/Chart.yaml
- helm/volsync/README.md
- helm/volsync/templates/NOTES.txt
- mover-rclone/README.md
- mover-rsync/README.md
- pkg/cmd/volsync.go
Signed-off-by: Ryan Cook <rcook@redhat.com>
Link fix from README
Review
> link fix of readme

- pkg/cmd/set_replication.go
Issue:
When set-replication performs the manual sync, it waits for the sync to finish
on the source (trigger status == spec), then it immediately attempts to retrieve
the latest images from the ReplicationDestination. There is no guarantee that
the latest image has been updated yet, even though we know the sync has been 
completed from the PoV of the source.
Solution:
1. Check destination and remember what we find
2. Do the manual sync on the source
3. Poll the destination until it's different than what we saw in step 1 (or timeout)
Fixes #14
Signed-off-by: Vinayakswami Hariharmath <vharihar@redhat.com>
> Race in set-replication

- helm/volsync/README.md
- Adds documentation to the Helm Chart README that describes the new options for specifying container images (by SHA hash).
- Also updates the general overview to include restic and expended list of use-cases
Docs for #5, #42
> Update Helm readme w/ description of *.image

- mover-rclone/Dockerfile
- mover-restic/Dockerfile
This PR builds the rclone and restic binaries from source instead of relying on the built binary releases.
Related to #73
> Build restic and rclone from source

- controllers/mover/restic/restic_test.go
- controllers/rclone_mover_test.go
This PR introduces a couple of Eventually blocks to await the initial resources used in the tests, which will sometimes be unavailable.
Fixes issues #41 and #57
> Adds Eventually Blocks To Rclone & Restic Tests

- Makefile
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
Upgrades the scaffolding to operator-sdk v1.15.0
> Upgrade to operator-sdk v1.15.0

- controllers/rclone_mover_test.go
For: https://github.com/backube/volsync/issues/117
rclone unit tests included one that does multiple syncs. Each sync creates a snapshot and the code
uses a timestamp (with granularity of seconds).  The test could sometimes run within 1 second so the 
2nd snapshot would attempt to re-use the same timestamp.  Alter the test so it will sleep if necessary
to avoid this.  The snapshot using timestamp of seconds shouldn't actually be a problem in normal operation.
Fixes: #117
> Fix rclone unit test for intermittent error

- kubectl-volsync/cmd/relationship.go
- kubectl-volsync/cmd/relationship_test.go
resource.Quantity doesn't serialize/deserialize properly via Viper because its fields are private. This adds SetData and GetData calls that:
1) Flatten the structure so that the quantity's string value can be set without destroying the rest of the data
2) Add a decoding hook to properly unmarshal the Capacity from a string
> Add (de-)serialization for resource.Quantity

- .github/workflows/operator.yml
- examples/syncthing/dokuwiki.yaml
- examples/syncthing/setup.sh
- examples/syncthing/syncthing.yaml
- mover-syncthing/Dockerfile
- mover-syncthing/Makefile
- mover-syncthing/config.xml
- mover-syncthing/entry.sh
> Adds Syncthing as a data mover in VolSync

- docs/usage/rsync/database_example_cross_cluster.rst
- docs/usage/rsync/index.rst
- examples/rsync/volsync_v1alpha1_replicationdestination_remotecluster.yaml
- examples/rsync/volsync_v1alpha1_replicationsource_remotecluster.yaml
Usage docs - additional rsync example for cross cluster scenario.  We think cross cluster is most likely the 
most common user scenario at this point.
> Adding usage example for rsync in a cross cluster scenario

- controllers/mover/rsync/rsync_test.go
- controllers/rclone_mover_test.go
- controllers/replicationdestination_test.go
- controllers/replicationsource_test.go
- kubectl-volsync/cmd/suite_test.go
- test-kuttl/e2e/restic-with-previous/20-assert.yaml
- test-kuttl/e2e/restic-with-previous/20-verify-data-doesnt-match.yaml
- test-kuttl/e2e/restic-with-restoreasof/20-assert.yaml
- test-kuttl/e2e/restic-with-restoreasof/20-verify-data-doesnt-match.yaml
- test-kuttl/e2e/restic-with-restoreasof/21-remove-restorecr-and-verify-job.yaml
- test-kuttl/e2e/restic-with-restoreasof/50-assert.yaml
- test-kuttl/e2e/restic-with-restoreasof/50-verify-data-doesnt-match-current.yaml
Provides attempted fixes for some unit test flakes that have been happening lately
Fixes #130
> Fixes for unit test flakes

- docs/usage/restic/database_example.rst
Fixing indentation for restic block in ReplicationSource example
None
None
> Fixing indentation in ReplicationSource example

- .github/workflows/documentation.yml
> Build docs on ocm- and release- branches as well as main

- docs/installation/development.rst
- docs/installation/index.rst
- docs/installation/rbac.rst
Provides a sample ClusterRole to grant users access to VolSync CRs so they can manage their own data replication.
Fixes #161
> Docs: RBAC to grant users access to VolSync CRs

- .github/workflows/operator.yml
- Procedures.md
- hack/setup-kind-cluster.sh
- Upgrades KinD to 0.12.0
- Updates the patch versions of kube we test against
- Blocked by #185
> Update kind to 0.12.0

- docs/usage/rsync/index.rst
Updates apiVersion in Rsync usage docs
No
None
> Update apiVersion in rsync docs

- .github/workflows/operator.yml
- go.mod
- go.sum
Break the CI tests if `go.mod` or `go.sum` are not current.
> Add a check to make sure go.mod/sum is up-to-date

- controllers/mover/events.go
- controllers/mover/mover.go
- controllers/mover/rclone/builder.go
- controllers/mover/restic/builder.go
- controllers/mover/rsync/builder.go
- controllers/mover/rsync/mover.go
- controllers/utils/utils.go
- controllers/volumehandler/new.go
- controllers/volumehandler/volumehandler.go
This adds Event publishing to the Rsync mover and to the Volumehandler
Related to: #67 
Depends on: #194
> Add events to Rsync mover

- kubectl-volsync/cmd/relationship.go
When updating the CLI relationship files, it was not possible to delete an option once it had been written into the file.
Example:
```console
$ ./bin/kubectl-volsync replication -r test create
$ ./bin/kubectl-volsync replication -r test set-destination --destination dst/datavol --volumesnapshotclass bad
$ ./bin/kubectl-volsync replication -r test set-destination --destination dst/datavol
```
The above set of commands should have removed the VSC from the relationship file, but it did not. This is due to Viper not supporting the removal of keys. When we attempt to set a key to `nil`, it just retains the old value.
With this patch, we actually create a new Viper instance and swap it out in order to get the intended effect.
**Is there anything that requires …
> CLI: Properly overwrite deleted config options

- docs/usage/rclone/index.rst
- docs/usage/restic/database_example.rst
- docs/usage/restic/index.rst
- examples/rclone/volsync_v1alpha1_replicationdestination.yaml
- examples/rclone/volsync_v1alpha1_replicationsource.yaml
- hack/run-minio.sh
Updates the docs with more information about how to define paths to S3 buckets (for rclone and rsync scenarios).
Not sure I covered all the scenarios or all the info needed about security considerations.  Anything else we should add or any other specific examples?
Fixes: https://github.com/backube/volsync/issues/165
> Doc multiple pvcs per s3

- Makefile
- bundle.Dockerfile
- bundle/manifests/volsync.backube_replicationdestinations.yaml
- bundle/manifests/volsync.backube_replicationsources.yaml
- bundle/manifests/volsync.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/crd/bases/volsync.backube_replicationdestinations.yaml
- config/crd/bases/volsync.backube_replicationsources.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
- config/rbac/role.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
- helm/volsync/crds/volsync.backube_replicationdestinations.yaml
- helm/volsync/crds/volsync.backube_replicationsources.yaml
- helm/volsync/templates/deployment-controller.yaml
- helm/volsync/values.yaml
Upgrades the operator scaffolding & support libraries to be consistent w/ operator-sdk v1.20.0
> Upgrade to operator-sdk v1.20.0

- Procedures.md
- docs/usage/cli/index.rst
Updates the docs w/ instructions on how to install the CLI via:
- krew
- binary release
- source (updated)
> Update docs to include CLI install via krew

- docs/design/index.rst
- docs/design/rwo-affinity.rst
- hack/run-minio.sh
Provides a design for how we can run movers against live RWO volumes (no clone/snapshot)
Design for: #17
> Add design doc for RWO mover affinity

- sonar-project.properties
Adds a config file for SonarCloud, but doesn't add the code coverage metrics due to issues w/ securely handling the account token.
Supersedes #230
> Add sonarcloud configuration

- CHANGELOG.md
- Makefile
- Procedures.md
- bundle.Dockerfile
- bundle/manifests/volsync-manager-config_v1_configmap.yaml
- bundle/manifests/volsync.backube_replicationdestinations.yaml
- bundle/manifests/volsync.backube_replicationsources.yaml
- bundle/manifests/volsync.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/crd/bases/volsync.backube_replicationdestinations.yaml
- config/crd/bases/volsync.backube_replicationsources.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/controller_manager_config.yaml
- config/manager/manager.yaml
- config/scorecard/patches/basic.config.yaml
- config/scorecard/patches/olm.config.yaml
- helm/volsync/Chart.yaml
- helm/volsync/crds/volsync.backube_replicationdestinations.yaml
- helm/volsync/crds/volsync.backube_replicationsources.yaml
- helm/volsync/templates/deployment-controller.yaml
- helm/volsync/values.yaml
- main.go
Upgrades scaffolding to sdk 1.22
This looks like it's starting to scaffold some of the new security stuff that we're going to need to address soon.
> Upgrade operator-sdk to v1.22.0

- controllers/mover/rclone/mover.go
- controllers/mover/restic/mover.go
- controllers/mover/rsync/mover.go
- controllers/mover/rsync/rsync_test.go
Modifies job reconciles to not modify the job.spec.template except on initial create.
For release-0.4 we don't have any critical changes in the movers that would require the job to be recreated - we can wait until the job finishes and then next cycle a new one will be created.
https://github.com/backube/volsync/issues/291
> Do not update running job.spec.template

- bundle/manifests/volsync.backube_replicationsources.yaml
- bundle/manifests/volsync.clusterserviceversion.yaml
- config/manager/kustomization.yaml
The bundle files didn't get updated with the Syncthing mover PR. This includes the updated files in the bundle.
Follow-on to #134
> Update bundle files from syncthing merge

- hack/setup-kind-cluster.sh
This enables the new "Pod Security Admission" feature on 1.23 and later kind clusters. It's set up to issue warnings for any workloads that aren't compliant w/ the "restricted" profile.
Example:
```console
$ kubectl create ns test
namespace/test created
$ kubectl get ns/test -oyaml
apiVersion: v1
kind: Namespace
metadata:
creationTimestamp: "2022-06-29T19:50:59Z"
labels:
kubernetes.io/metadata.name: test
name: test
resourceVersion: "871"
uid: e72750d7-0f8d-4307-ab42-0d3be8b1b484
spec:
finalizers:
- kubernetes
status:
phase: Active
$ kubectl -n test apply -f ~/src/ocp4/manifests/centos_3g.yaml 
persistentvolumeclaim/datavol created
Warning: would violate PodSecurity …
```
> Enable Pod Security Admission in kind

- CHANGELOG.md
- bundle/manifests/volsync.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- helm/volsync/Chart.yaml
- helm/volsync/templates/deployment-controller.yaml
Updates the kube-rbac-proxy image to v0.13.0
> Update kube-rbac-proxy to v0.13.0

- .github/workflows/documentation.yml
- .github/workflows/operator.yml
- .github/workflows/registry-push.yml
This is a follow-on to #307 that will enable triggering periodic builds in the release-0.4 branch
> Backport GH actions changes to enable periodic builds

- .github/workflows/periodic.yml
Hopefully the last in the series to get periodic builds for release branches
- #266
- #307
- #315
- #318
> Enable periodic builds of release-0.4

- controllers/mover/syncthing/mover.go
Signed-off-by: Oleg <97077423+RobotSail@users.noreply.github.com>
> logs dns used for certificates

- hack/setup-kind-cluster.sh
This updates the CSI hostpath driver on the kind cluster to 1.9.
v1.9 includes a change that enables [fsGroup policy](https://kubernetes-csi.github.io/docs/support-fsgroup.html#csi-volume-fsgroup-policy) so that volumes can be made writable by non-root.
I have also enabled fsGroup policy for 1.20 clusters (when it 1st entered beta) by manually updating the CSIDriver object since the v1.7 release required for 1.20 support doesn't support it.
> Update hostpath driver to v1.9 & enable fsGroup

- .github/workflows/periodic.yml
release-0.5 branch has been created. This enables the weekly builds for the branch.
> ci: Enable periodic builds of release-0.5

- Procedures.md
- bundle/manifests/volsync.clusterserviceversion.yaml
- config/manifests/bases/volsync.clusterserviceversion.yaml
Updates the volsync description in the CSV.
- Updated the csv in config/manifest/bases and then ran `make bundle`.
- Will need to cherry-pick into release-0.5
> Update VolSync description in csv

- bundle/manifests/volsync.clusterserviceversion.yaml
- config/manifests/bases/volsync.clusterserviceversion.yaml
- helm/volsync/README.md
fixes typo in the csv description & helm readme
> Fix typo in readme/csv description

- bundle/manifests/volsync.clusterserviceversion.yaml
- config/manifests/bases/volsync.clusterserviceversion.yaml
- helm/volsync/README.md
Updates helm README and description in the operator CSV with suggestions from Chris.
> Doc update suggestions from Christopher Dawson

- test-e2e/dump_logs.yml
- test-e2e/roles/dump_logs/tasks/dump_namespace_contents.yml
- test-e2e/roles/dump_logs/tasks/dump_volsync_logs.yml
- test-e2e/roles/dump_logs/tasks/main.yml
- test-e2e/run_tests_in_parallel.sh
- Adds a playbook to describe objects from test namespaces and dump volsync controller logs
- Runs the playbook if tests fail
> Tests: Dump logs playbook

- test-e2e/Pipfile
- test-e2e/Pipfile.lock
- test-e2e/README.md
- test-e2e/requirements.yml
- test-e2e/roles/pvc_has_data/meta/main.yml
- test-e2e/roles/pvc_has_data/tasks/main.yml
- test-e2e/roles/pvc_has_data/templates/pod.yml.j2
- test-e2e/roles/test_syncthing_cluster_sync/tasks/await_connected.yml
- test-e2e/roles/test_syncthing_cluster_sync/tasks/connect.yml
- test-e2e/roles/test_syncthing_cluster_sync/tasks/main.yml
- test-e2e/roles/write_to_pvc/templates/pod.yml.j2
- test-e2e/test_syncthing_cluster_sync.yml
Ports over the syncthing e2e test
> Tests: Add ansible-based Syncthing e2e

- test-e2e/test_multi_sync_snapshot_rclone.yml
- test-e2e/test_multi_sync_snapshot_rsync.yml
Converts the remaining rclone and rsync tests to ansible
> Port remaining rsync/rclone tests to Ansible

- test-e2e/roles/test_syncthing_cluster_sync/tasks/connect.yml
Limits the size of the patch operation to hopefully prevent issues when connecting the syncthing instances together
Fixes #355
> tests: Use a smaller patch to connect syncthings

- test-e2e/roles/cli/handlers/main.yml
- test-e2e/roles/cli/tasks/main.yml
- test-e2e/roles/cli/tasks/setup.yml
- test-e2e/roles/compare_pvc_data/tasks/main.yml
- test-e2e/roles/compare_pvc_data/templates/pod.yml.j2
- test-e2e/roles/pvc_has_data/tasks/main.yml
- test-e2e/roles/pvc_has_data/templates/pod.yml.j2
- test-e2e/roles/write_to_pvc/templates/pod.yml.j2
- test-e2e/test_replication_sched_snap.yml
- test-e2e/test_replication_sync_direct.yml
- test-e2e/test_roles.yml
- Converts the CLI tests to Ansible
- Fixes the PVC manipulation/comparison roles
- Adds a test to make sure the PVC roles are working properly :sob: 
- Adds ability to "negatively" test using the roles via `should_fail` bool
> Tests: Port over CLI tests

- mover-restic/entry.sh
- Trying to debug openshift/release#31509
- We should have this output anyway
> restic: Dump the output of repo probe when we get an unexpected response

- Makefile
- test-e2e/Pipfile.lock
- test-e2e/roles/compare_pvc_data/tasks/main.yml
- test-e2e/roles/pvc_affinity_pod/tasks/main.yml
- test-e2e/roles/pvc_has_data/tasks/main.yml
- test-e2e/roles/write_to_pvc/tasks/main.yml
- test-e2e/run_tests_in_parallel.sh
- test-e2e/test_multi_sync_snapshot_rclone.yml
- test-e2e/test_multi_sync_snapshot_rsync.yml
- test-e2e/test_replication_sched_snap.yml
- test-e2e/test_replication_sync_direct.yml
- test-e2e/test_restic_with_manual_trigger.yml
- test-e2e/test_restic_with_previous.yml
- test-e2e/test_restic_with_restoreasof.yml
- test-e2e/test_simple_rclone.yml
- test-e2e/test_simple_rsync.yml
Adjusts step timeouts to try and get the e2e tests passing more consistently. We don't seem to be running into any actual failures, just timeouts due to not waiting long enough.
> CI: Adjust test timeouts

- controllers/platform/properties.go
Typo fix for https://github.com/backube/volsync/pull/413#discussion_r964950154
> Fix typo in comment

- CHANGELOG.md
- helm/volsync/Chart.yaml
Updates changelog and helm charts so we can make the 0.5.0 release
- This will need to be cherry-picked into the `release-0.5` branch.
- Not sure I got everything in the changelog - anything I missed?
> Update changelog and helm for 0.5.0 release

- controllers/mover/restic/mover.go
- controllers/mover/restic/restic_test.go
- docs/usage/restic/index.rst
Backport of #407 to release-0.5
> [release-0.5] Allow passing in GOOGLE_APPLICATION_CREDENTIALS

- .ci-scripts/mdl-style.rb
- CHANGELOG.md
Update the list of fixed items that will go into the 0.5.1 release
> changelog update for 0.5.1

- .ci-scripts/mdl-style.rb
Brings the fixes to the mdl linter configuration to the release-0.4 branch
> [release-0.4] cherry-pick the mdl fixes

- controllers/platform/properties_test.go
> [release-0.6] Unit test fix - cleanup SCC crd in-between tests

- .github/workflows/operator.yml
- mover-rsync-tls/Dockerfile
- mover-rsync-tls/Makefile
- mover-rsync-tls/client.sh
- mover-rsync-tls/server.sh
Adds a new rsync-based mover that uses stunnel instead of ssh for the transport.
#364
> Add new rsync-tls mover

- .github/workflows/periodic.yml
Adds periodic builds for the release-0.6 branch
> CI: Enable periodic builds of release-0.6 branch

- mover-rclone/Dockerfile
Updates rclone to the latest release (v1.60.1)
Resolves: https://github.com/backube/volsync/issues/534
> Update rclone to v1.60.1

- docs/index.rst
- docs/usage/index.rst
- docs/usage/permissionmodel.rst
- docs/usage/rsync-tls/index.rst
- docs/usage/rsync-tls/mysql-migration.rst
- docs/usage/rsync/index.rst
> rsync-tls: Add documentation for new rsync-tls mover

- hack/setup-kind-cluster.sh
This updates the version of the CSI hostpath driver to be the latest supported on each kube version
> ci: Update the version of csi hostpath driver

- .github/workflows/documentation.yml
- .github/workflows/operator.yml
- .github/workflows/periodic.yml
- .github/workflows/registry-push.yml
- .github/workflows/stale.yml
Annotates all the GH actions hashes with their corresponding tag
Fixes #492
> Annotate gh action versions w/ their tag

- CHANGELOG.md
- helm/volsync/Chart.yaml
- updates the CHANGELOG.md with updates for the 0.6.0 release.
- also updates the helm chart to version 0.6.0 and updates gpg signing key
> changelog and helm updates for 0.6.0

- CHANGELOG.md
> Update changelog for prev 0.5.2 and also update changelog for upcoming 0.6.1 release

- bundle/manifests/volsync.clusterserviceversion.yaml
- helm/volsync/Chart.yaml
- version.mk
> Versioning for v0.6.1

- OWNERS
> Add Valentina (https://github.com/birsanv) to OWNERS

- CHANGELOG.md
- Dockerfile
- go.mod
- go.sum
> Update syncthing to v1.23.1

- CHANGELOG.md
- Dockerfile
> Upgrade rclone to v1.61.1

- .github/workflows/periodic.yml
- Procedures.md
Enable periodic builds of the release-0.7 branch
> Enable periodic builds of release-0.7

- custom-scorecard-tests/config.yaml
- custom-scorecard-tests/scorecard/patches/deploy-prereqs.yaml
- custom-scorecard-tests/scorecard/patches/e2e-tests.yaml
Updates custom scorecard config.yaml to use the custom-scorecard image for release-0.7
> Update cust scorecard tests yamls for release-0.7

- CHANGELOG.md
> Changelog updates for v0.7.0

- bundle/manifests/volsync.clusterserviceversion.yaml
- helm/volsync/Chart.yaml
- version.mk
> v0.7.1 for upcoming .z release

- .readthedocs.yml
See: https://github.com/readthedocs/readthedocs.org/issues/10290
> Update readthedocs config to use python 3.11

- bundle/manifests/volsync.clusterserviceversion.yaml
- helm/volsync/Chart.yaml
- version.mk
Updates version to v0.7.2 in the release-0.7 branch for upcoming 0.7.2 release
> Version v0.7.2

- go.mod
- go.sum
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>
just a version upgrade corresponding to 4.13
> `go get github.com/openshift/api@release-4.13 && go mod tidy`

- CHANGELOG.md
- Dockerfile
> Upgrade Rclone to v1.62.2

- bundle/manifests/volsync.clusterserviceversion.yaml
- version.mk
> versioning for v0.7.3

- bundle/manifests/volsync.clusterserviceversion.yaml
- version.mk
> v0.5.4 - for downstream to pkg with updated rbac-proxy img

- bundle/manifests/volsync.clusterserviceversion.yaml
- version.mk
> v0.6.3 - for downstream to pkg with updated rbac-proxy img

- CHANGELOG.md
- Dockerfile
> Update rclone to v1.63.1

- bundle/manifests/volsync.clusterserviceversion.yaml
- version.mk
- release built with golang 1.20 for future downstream maintenance
> version v0.5.5

- bundle/manifests/volsync.clusterserviceversion.yaml
- version.mk
- release built with golang 1.20 for future downstream maintenance
> version v0.6.4

- CHANGELOG.md
- docs/usage/index.rst
- docs/usage/rclone/database_example.rst
- docs/usage/restic/database_example.rst
- docs/usage/rsync/database_example.rst
- docs/usage/volume-populator/index.rst
- examples/destination-database/mysql-pvc.yaml
- examples/rclone/rclone.conf
- examples/rclone/volsync_v1alpha1_replicationdestination.yaml
- examples/rclone/volsync_v1alpha1_replicationsource.yaml
> Volume populator docs

- api/v1alpha1/replicationdestination_types.go
- api/v1alpha1/replicationsource_types.go
- bundle/manifests/volsync.backube_replicationdestinations.yaml
- bundle/manifests/volsync.backube_replicationsources.yaml
- bundle/manifests/volsync.clusterserviceversion.yaml
- config/crd/bases/volsync.backube_replicationdestinations.yaml
- config/crd/bases/volsync.backube_replicationsources.yaml
- controllers/statemachine/machine_test.go
- helm/volsync/templates/volsync.backube_replicationdestinations.yaml
- helm/volsync/templates/volsync.backube_replicationsources.yaml
- mover-restic/entry.sh
- mover-rsync-tls/client.sh
Improves the regex validation in the CRD for the schedule cronspec
Shellcheck alerted on a couple other issues which are fixed in a separate commit
Fixes #847
> Fix cronspec validation

- CHANGELOG.md
- Dockerfile
> Update rclone to v1.64.0

- controllers/volumepopulator_controller_test.go
- make sure vol pop controller  has done PV rebind to PVC (from pvcPrime) before simulating pvcPrime
claimLost and PV rebind completion
Fixes: https://github.com/backube/volsync/issues/863
> unit test- timing update

- controllers/mover/rclone/suite_test.go
- controllers/mover/restic/suite_test.go
- controllers/mover/rsync/suite_test.go
- controllers/mover/rsynctls/suite_test.go
- controllers/mover/syncthing/suite_test.go
- controllers/suite_test.go
- controllers/volumehandler/suite_test.go
- go.mod
- go.sum
- main.go
> Update controller-runtime to v0.16.2

- Dockerfile
- diskrsync-tcp/main.go
- renovate.json5
- Will help with downstream builds so downstream can be as close to upstream as possible
- Also update to set a version (and print it out in the log) for diskrsync-tcp
> git clone and run go build for diskrsync

- Makefile
- renovate.json5
Adds yq to the list of packages updated by renovate
Fixes #894
> Enable auto-update of yq

- renovate.json5
> Renovate: Group syncthing updates into single PR

- .github/workflows/operator.yml
- hack/setup-kind-cluster.sh
> Update the versions of kube we test on

- controllers/mover/rclone/mover.go
- controllers/mover/rclone/rclone_test.go
- controllers/mover/restic/mover.go
- controllers/mover/restic/restic_test.go
- controllers/mover/rsync/mover.go
- controllers/mover/rsync/rsync_test.go
- controllers/mover/rsynctls/mover.go
- controllers/mover/rsynctls/rsync_test.go
- controllers/mover/syncthing/mover.go
- controllers/mover/syncthing/syncthing_test.go
- controllers/utils/cleanup_test.go
- go.mod
- go.sum
- kubectl-volsync/cmd/replication_test.go
- move to k8s.io/utils/ptr instead of deprecated k8s.io/utils/pointer
> Uppdate k8s.io/utils digest to 3b25d92

- CHANGELOG.md
- Dockerfile
- update comment in Dockerfile to be consistent
> CHANGELOG update syncthing v1.25.0

- custom-scorecard-tests/config.yaml
- custom-scorecard-tests/scorecard/patches/deploy-prereqs.yaml
- custom-scorecard-tests/scorecard/patches/e2e-tests.yaml
> Update custom-scorecard-tests img tag release-0.8

- .github/workflows/periodic.yml
> Enable periodic builds of release-0.8

- CHANGELOG.md
- helm/volsync/Chart.yaml
- kubectl-volsync/volsync.yaml
> Post-release v0.8.0 updates: changelog, charts etc

- CHANGELOG.md
> Update changelog for syncthing v1.26.0

- docs/installation/index.rst
Adds some basic info to the docs for users that want to use VolSync w/ Longhorn
Closes #813
> docs: Add Longhorn CSI info

- docs/usage/volume-populator/index.rst
Fixes: https://github.com/backube/volsync/issues/988
> Docs - Fix incorrect storageClassName in vol pop example

- mover-restic/entry.sh
https://github.com/backube/volsync/issues/1004
> restic restore run cmd separately to capture error

- .github/workflows/operator.yml
- .github/workflows/registry-push.yml
> Update actions upload & download artifact to v4

- controllers/mover/restic/mover.go
Fixes: https://github.com/backube/volsync/issues/1069
- RESTIC_REST_USERNAME
- RESTIC_REST_PASSWORD
- AZURE_ENDPOINT_SUFFIX
https://github.com/backube/volsync/issues/1069
> Pass through additional restic env vars

- .github/workflows/stale.yml
> PRs that have "hold" label should not be marked stale

- bundle/manifests/volsync.clusterserviceversion.yaml
- config/manager/manager.yaml
- helm/volsync/values.yaml
> update mem limit in olm deployments of volsync

- custom-scorecard-tests/config.yaml
- custom-scorecard-tests/scorecard/patches/deploy-prereqs-stage0.yaml
- custom-scorecard-tests/scorecard/patches/e2e-tests-stage1.yaml
- custom-scorecard-tests/scorecard/patches/e2e-tests-stage2.yaml
> Update custom-scorecard-tests img tag release-0.9

- .github/workflows/periodic.yml
> Enable periodic builds of release-0.9

- docs/usage/index.rst
- docs/usage/pvccopytriggers.rst
> docs - pvc annotations for copy triggers

- .github/workflows/operator.yml
> Remove some older kube versions from test matrix

- CHANGELOG.md
- helm/volsync/Chart.yaml
- kubectl-volsync/volsync.yaml
> Post release v0.9.0 update changelog/charts etc

- CHANGELOG.md
- helm/volsync/Chart.yaml
- kubectl-volsync/volsync.yaml
Post release v0.9.0 update changelog/charts etc
(cherry picked from commit f16c6cd513f8ca7f1e83bc5dcc36a9fc68622755)
cherry-pick to update files in release-0.9 branch (original PR in main: https://github.com/backube/volsync/pull/1175)
> [release-0.9] Merge pull request #1175 from tesshuflower/changelog_and_helm_for_v0.9.0

- bundle/manifests/volsync.clusterserviceversion.yaml
- version.mk
> Create version for v0.9.1

- CHANGELOG.md
- helm/volsync/Chart.yaml
- kubectl-volsync/volsync.yaml
Updates changelog, helm charts and kubectl-volsync/volsync.yaml (this file was generated from release-0.9 branch but I think it makes sense to commit these here in main and then cherry-pick into release-0.9).  Currently helm charts are the same in main as in release-0.9.
> post release v0.9.1 update changelog/charts etc

- api/v1alpha1/replicationdestination_types.go
- api/v1alpha1/replicationsource_types.go
- bundle/manifests/volsync.backube_replicationdestinations.yaml
- bundle/manifests/volsync.backube_replicationsources.yaml
- bundle/manifests/volsync.clusterserviceversion.yaml
- config/crd/bases/volsync.backube_replicationdestinations.yaml
- config/crd/bases/volsync.backube_replicationsources.yaml
- config/manifests/bases/volsync.clusterserviceversion.yaml
- helm/volsync/templates/volsync.backube_replicationdestinations.yaml
- helm/volsync/templates/volsync.backube_replicationsources.yaml
> api description updates for RS and RD

- bundle/manifests/volsync.clusterserviceversion.yaml
- version.mk
> version for v0.9.2

- .github/workflows/operator.yml
> Add kube 1.30.0 to e2e test matrix

- .github/workflows/periodic.yml
> build release-0.10 periodically

- custom-scorecard-tests/config.yaml
- custom-scorecard-tests/scorecard/patches/e2e-tests-stage1.yaml
- mover-rsync-tls/client.sh
- test-e2e/roles/write_to_pvc/tasks/main.yml
- test-e2e/roles/write_to_pvc/templates/job.yml.j2
- test-e2e/test_rsync_tls_normal_manyfiles.yml
Cherry pick of https://github.com/backube/volsync/pull/1291 to release-0.9
> [release-0.9] Cherry pick rsynctls toomanyfiles

- controllers/utils/sahandler.go
- docs/usage/index.rst
- docs/usage/moverserviceaccount.rst
https://github.com/backube/volsync/issues/1296
> Doc update moverserviceaccount

- mover-rsync-tls/server.sh
> more logging in server side rsync-tls script

- CHANGELOG.md
- helm/volsync/Chart.yaml
- kubectl-volsync/volsync.yaml
Will probably cherry-pick this into release-0.10 just to be consistent.
> update changelog, charts etc for v0.10.0 release

- custom-scorecard-tests/config-downstream.yaml
- custom-scorecard-tests/config.yaml
- custom-scorecard-tests/scorecard/bases/patches/deploy-prereqs-stage0.yaml
- custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage1.yaml
- custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage2.yaml
> Update custom-scorecard-tests for release-0.11

- .github/workflows/periodic.yml
> build release-0.11 periodically

- .github/workflows/periodic.yml
> remove periodic builds of branches < release-0.9

- .github/workflows/documentation.yml
- .github/workflows/operator.yml
- .github/workflows/periodic.yml
> Ci ubuntu 24.x

- CHANGELOG.md
- helm/volsync/Chart.yaml
- kubectl-volsync/volsync.yaml
updates to changelog, charts.yaml and kubectl volsync.yaml now that we've published v0.11.0.
I should probably cherry-pick this into release-0.11 as well.
> changelog, charts.yaml, kubectl updates for v0.11.0

- go.mod
- go.sum
> update x/net for CVE-2024-45338

- helm/volsync/Chart.yaml
> version charts for v0.12.0-rc.2

- helm/volsync/Chart.yaml
> Update to v0.12.0 in helm Charts.yaml

- CHANGELOG.md
- kubectl-volsync/volsync.yaml
- also update kubectl-volsync/volsync.yaml
> update changelog after publishing v0.12.0

- .github/workflows/operator.yml
> Add kube v1.32 to e2e test matrix

- .ci-scripts/yamlconfig.yaml
- .github/workflows/operator.yml
- .github/workflows/release.yml
- .krew.yaml
- renovate.json5
> Rh release workflow for volsync-kubectl

- .github/workflows/operator.yml
- kubectl-volsync/volsync.yaml
This build aarch64 image. If this gets merge I will prepare another change which will merge both images and upload it to registry.
https://github.com/backube/volsync/issues/828
https://github.com/backube/volsync/issues/574
> build aarch64 image

- .github/workflows/operator.yml
- .github/workflows/registry-push.yml
Follow up on https://github.com/backube/volsync/pull/1605. It pushes multi arch image to registry.
> push multiarch images to registry

- .github/workflows/operator.yml
> gh workflow ffwd to release br

- .ci-scripts/yamlconfig.yaml
- Dockerfile.rhtap
- add Dockerfile.rhtap with golang builder, final img and fips flags for downstream (to be used by konflux)
> Dockerfile for konflux builds

- OWNERS
> add izmi to OWNERS

- .github/workflows/periodic.yml
> remove old periodic builds, add 0.12 and 0.13

- CHANGELOG.md
> update changelog for v0.13.1

- .github/workflows/operator.yml
> add kube v1.34.0 to e2e test matrix
