api/v1alpha1/replicationdestination_types.go
api/v1alpha1/replicationsource_types.go
controllers/mover/mover.go
controllers/mover/restic/mover.go
controllers/mover/restic/restic_test.go
controllers/replicationdestination_test.go
controllers/replicationsource_test.go
controllers/utils/utils.go
controllers/volumehandler.go
controllers/volumehandler/new.go
controllers/volumehandler/volumehandler.go
controllers/volumehandler/volumehandler_test.go

Fixes the import lines to use `corev1` and the standard alias for the `core/v1` package
Fixes #3

Fix import alias of core/v1 to always be corev1

---

controllers/mover/restic/restic_test.go
hack/run-in-kind.sh
hack/run-minio.sh

During the unit tests, it can take some time for objects to be visible (Get-able) after they are created. This change forces the test setup to wait until the precreated PVC is visible prior to starting the test.
Fixes #6

Fix restic test

---

codecov.yml

The codecov checks are intended to be advisory, reminding developers to write appropriate tests, but it's not meant to enforce a certain level of coverage. This keeps the codecov status checks from failing. Since it doesn't look like we can configure Prow to ignore optional checks, we need to have codecov always pass.

Update codecov to not fail on poor coverage

---

CHANGELOG.md
helm/volsync/Chart.yaml

Updates for the v0.3 release of VolSync
This will be the 1st release under the VolSync name and allow us to complete the switchover from the Scribe name by publishing a new Helm chart pointing to this release.
- backube/helm-charts#10
- backube/scribe#217

Updates for 0.3.0 release

---

helm/volsync/templates/_helpers.tpl
helm/volsync/templates/deployment-controller.yaml
helm/volsync/values.yaml

This adds an additional field to the Chart values file that allows specifying the full image field unstead of individually specifying the image and tag. The purpose is to permit specifying the image+sha hash.
Note:
`x.image` overrides both `x.repository` and `x.tag`
Fixes #5

Add ability to specify full container image in Chart

---

pkg/cmd/create_replication.go
pkg/cmd/destination.go
pkg/cmd/resource_options.go
pkg/cmd/set_replication.go

start-replication allows creating a custom named ReplicationSource
via the source-name parameter. set-replication should also use this
parameter since it's commonly used as part of a start, set sequence.
Due to different source and destination names used for command line
parameters in case of start-replication and set-replication, the
set-replication command tries to find the replication destination
and replication source in default namespaces and fails.
corrected command-line parameters as mentioned in
https://scribe-replication.readthedocs.io/en/latest/usage/rsync/plugin_opts.html
Fixes #50
Fixes #10
Signed-off-by: Vinayakswami Hariharmath <vharihar@redhat.com>

cli: set-replication doesn't obey source-name

---

docs/usage/rsync/db_example_cli.rst
docs/usage/rsync/multi_context_sync_cli.rst
docs/usage/rsync/plugin_opts.rst
pkg/cmd/resource_options.go
pkg/cmd/set_replication.go
pkg/cmd/volsync.go

Signed-off-by: Sally O'Malley <somalley@redhat.com>
This PR:
* fixes the error handling when ignoring viper.ConfigFileNotFound error
* updates `~/.volsyncconfig/config.yaml` to `~/.volsync/config.yaml` for config location
Fixes https://github.com/backube/volsync/issues/49

cli should be usable w/o a config file

---

test-kuttl/e2e/restic-with-manual-trigger/10-assert.yaml
test-kuttl/e2e/restic-with-manual-trigger/20-assert.yaml
test-kuttl/e2e/simple-rclone/10-create-destination.yaml
test-kuttl/e2e/simple-rclone/16-assert.yaml
test-kuttl/e2e/simple-rsync/15-create-source.sh
test-kuttl/e2e/simple-rsync/30-assert.yaml

This increases the timeout for test steps that use volumes created from snapshots. This is necessary because cloud providers can take a while for Snapshots to become ready to use. It also increases the sync interval to ensure we don't start a new sync while waiting for snapshots from the previous.

Increase e2e timeout when waiting for snapshots

---

.github/workflows/operator.yml

This adds moving tags to the container images in Quay that will track
the HEAD of the release and ocm branches.
open-cluster-management/backlog#14604

Adds moving image tags for release & ocm branches

---

.github/workflows/operator.yml
hack/setup-kind-cluster.sh

- Updates to latest kind kube images for all minor kube versions
- Switches default kind cluster to 1.22
- Adds 1.22 to the test matrix

Add Kube 1.22 to the test matrix

---

controllers/mover/restic/mover.go
controllers/mover/restic/restic_test.go
controllers/rclone_mover_test.go
controllers/replicationdestination_controller.go
controllers/replicationdestination_test.go
controllers/replicationsource_controller.go
controllers/replicationsource_test.go
controllers/rsync_common.go
controllers/utils/sahandler.go
controllers/utils/utils.go
controllers/volumehandler.go
controllers/volumehandler/volumehandler.go
controllers/volumehandler/volumehandler_test.go

NameFor is functionally equivalent to OKFO, so this commit replaces our
custom implementation w/ OKFO.

Replace utils.NameFor w/ client.ObjectKeyFromObject

---

OWNERS

Signed-off-by: Joshua Packer <jpacker@redhat.com>
Add additional owners and reviewers from Open Cluster Management community
This is adding owners, so must be reviewed/approved
None

Add more owners/reviewers

---

controllers/mover/builder.go
controllers/mover/restic/builder.go
main.go

The VersionInfo() call allows movers to print the container image that they will be using. This is useful information in the debug logs.
Fixes #78

Add VersionInfo to Builder interface

---

kubectl-volsync/cmd/client.go
kubectl-volsync/cmd/client_test.go
kubectl-volsync/cmd/migration_create.go

With the CLI, we're specifying in-cluster object names as `[contextname/]namespace/objectname`.
This adds parsing of that string into a struct that is also compatible w/ the frequently used NamespacedName struct
#82

Add parser for cross cluster resources

---

go.mod
kubectl-volsync/cmd/relationship.go
kubectl-volsync/cmd/relationship_test.go

We need to be able to track which in-cluster objects are associated with a particular relationship.
This code creates a UUID for each relationship that can be added as an annotation to the in-cluster objects.

Add an ID to relationships

---

Dockerfile
Makefile
mover-rclone/Dockerfile
mover-restic/Dockerfile

We don't vendor the modules, but some golang builder containers assume
we do. This forces vendor directories to be ignored.
- openshift/release#20036

Ensure golang modules are downloaded, not vendored

---

Dockerfile
mover-rclone/Dockerfile
mover-restic/Dockerfile

#91 didn't work as expected because the env var from the base container didn't get overwritten. Using ENV instead of ARG does overwrite.

Use ENV instead of ARG to override GOFLAGS

---

.github/workflows/operator.yml
Dockerfile
Procedures.md
go.mod
mover-rclone/Dockerfile
mover-restic/Dockerfile

Updates the version of golang used to build the operator from 1.16 to 1.17
openshift/release#23446

Update to golang 1.17

---

Makefile

We had been using the goreleaser script to dl/install golangci-lint, but that method is no longer maintained. This change switches to using the [recommended method](https://golangci-lint.run/usage/install/#other-ci) for install.
Fixes: #102

Update how golangci-list is installed

---

Dockerfile
mover-rclone/Dockerfile
mover-restic/Dockerfile
mover-rsync/Dockerfile

- Switches builder containers to ones that can use fips modules
- Enable CGO since that's required to call out to certified modules
- Add a command in the build process to ensure library hooks are in place
#105

Update container builds for FIPS compatibility

---

kubectl-volsync/cmd/relationship.go

Creates the configuration directory (default: `~/.volsync`) if it doesn't already exist. This fixes the problem where saving the relationship file would fail if the directory wasn't there.

CLI: create config directory if it doesn't exist

---

Dockerfile
Makefile

With the switch to the go-toolset builder container, it appears that an existing env variable was overriding how we were embedding the operator version during the build process. This changes the name of the build arg to avoid the collision.
See "Operator Version", below...
Bad:
```
[jstrunk main  volsync]$ kubectl -n volsync-system logs deploy/volsync -c manager
2022-01-28T14:21:16.840Z	INFO	setup	Go Version: go1.16.12
2022-01-28T14:21:16.841Z	INFO	setup	Go OS/Arch: linux/amd64
2022-01-28T14:21:16.841Z	INFO	setup	Operator Version: 1.16.12
2022-01-28T14:21:16.841Z	INFO	setup	Rsync container: quay.io/backube/volsync-mover-rsync:local-build
2022-01-28T14:21:16.841Z	INFO	setup	Rclone container: quay.io/backube/volsync-mover-rclone:local-build …
```

Fix operator version embedding

---

kubectl-volsync/cmd/migration.go
kubectl-volsync/cmd/migration_create.go
kubectl-volsync/cmd/migration_create_test.go

This sub-command should prepare a destination to receive incoming transfers from an external source.

CLI: Migration create

---

Makefile
go.mod
kubectl-volsync/cmd/relationship.go
kubectl-volsync/cmd/relationship_test.go
kubectl-volsync/cmd/replication.go
kubectl-volsync/cmd/replication_create.go
kubectl-volsync/cmd/replication_delete.go
kubectl-volsync/cmd/replication_test.go
kubectl-volsync/cmd/suite_test.go

Adds the `create` and `delete` commands to the `kubectl-volsync replication` sub-command

CLI replication create & delete

---

kubectl-volsync/cmd/migration.go
kubectl-volsync/cmd/migration_create.go
kubectl-volsync/cmd/migration_create_test.go
kubectl-volsync/cmd/migration_rsync.go

`kubectl migration rsync <args>`
Syncs data into an existing migration relationship using rsync over ssh

CLI: Migration rsync

---

helm/volsync/README.md
helm/volsync/templates/SCC-mover.yaml
helm/volsync/values.yaml

Adds a configuration option to the Helm chart that forces deployment of the custom mover SecurityContextConstraint. Normally, the existing autodetection is sufficient, but in cases where users want to template the chart without querying the cluster, it may be necessary to force the generation of the SCC.
Fixes: #140

Add option to force deployment of mover SCC

---

kubectl-volsync/cmd/migration.go
kubectl-volsync/cmd/migration_delete.go
kubectl-volsync/cmd/migration_delete_test.go

1. Removes the ReplicationDestination that is associated w/
the relationship (if it exists in-cluster)
2. Deletes the relationship config file
#83

CLI - Migration delete

---

.gitignore
bundle/tests/scorecard/config.yaml
config/scorecard/bases/config.yaml

config.yaml files were in .gitignore, so some generated files from initial bundle generation got missed.
This means subsequent make bundle commands could fail as they are missing some expected files.
I modified .gitignore to only ignore /config.yaml  - Is this correct?

Commit missed generated bundle scorecard config files

---

.ci-scripts/yamlconfig.yaml
.github/workflows/operator.yml
Makefile
kubectl-volsync/cmd/root.go
kubectl-volsync/volsync.yaml

Provides targets to build the manifest and artifact for distributing the CLI via krew
Fixes: #153

Add resources for submitting kubectl-volsync to krew

---

controllers/rclone_mover_test.go

Try to fix timing issue where loaded resource was expected to already be modified by the controller
https://github.com/backube/volsync/issues/158

Check lastSyncStartTime in Eventually loop to avoid timing issues

---

controllers/replicationdestination_test.go
controllers/replicationsource_test.go

Adds an Eventually() loop when checking the state of lastSyncStartTime to avoid race w/ controller updating it
Same approach as #171 
Fixes #179

tests: Add Eventually loop around lastSyncStartTime

---

bundle/manifests/volsync.clusterserviceversion.yaml
config/manager/manager.yaml
controllers/replicationdestination_controller.go
controllers/replicationsource_controller.go
hack/run-in-kind.sh
helm/volsync/values.yaml

Reconcile operations w/ a long latency cause the controller to be less responsive to other CRs in the system. This PR:
- Increases the CPU limit to allow CPU-intensive operations (key generation) to complete quicker
- Increases the max number of simultaneous reconciles from 1 for each CR type to 100 per type to enable cross-CR parallelism
I *think* this is the cause of the intermittent CI failures of the kuttl tests in #157. The CLI tests add additional tests that cause ssh keys to be generated.
I would like to just remove the CPU limit, but that increases the risk of collateral damage if VolSync were to get into a loop.

Increase operator responsiveness

---

.github/workflows/operator.yml

The job which builds the Syncthing container needs to complete before the e2e tests run. This adds the dependency to ensure that happens.

Add syncthing mover build as dependency for e2e

---

Makefile
Procedures.md
bundle/manifests/volsync.clusterserviceversion.yaml
config/manifests/bases/volsync.clusterserviceversion.yaml
version.mk

- adds MIN_KUBE_VERSION of 1.19.0 to version.mk
- Subsequent calls to `make bundle` will update the bundle csv to use this MIN_KUBE_VERSION.
- Sets the minKubeVersion in the bundle csv to 1.19.0

set minKubeVersion to 1.19.0 in CSV (added also to version.mk file)

---

hack/setup-kind-cluster.sh

Updates the script for the kind cluster to install the v5.0.0 version of the csi external-snapshotter.
It also changes to using the new kustomize-based installation.

Update kind cluster to use v5 of external-snapshotter

---

examples/syncthing/syncthing.yaml
mover-syncthing/entry.sh

Signed-off-by: Oleg <97077423+RobotSail@users.noreply.github.com>
This pull request aims to introduces the following changes to the Syncthing Mover image:
- A `SYNCTHING_CERT_DIR` environment variable is added which specifies where the volume containing the HTTPS certificates will be mounted in the Syncthing container 
If the variable is not defined or the Secret wasn't mounted in the container, the default Syncthing HTTPS certificates are used.
Otherwise, `entry.sh` will copy the `https-key.pem` and `https-cert.pem` files and place them in `$SYNCTHING_CONFIG_DIR` 

Add HTTPS Certificate Environment Variables for Syncthing Image

---

controllers/mover/rclone/mover.go
controllers/mover/restic/mover.go
controllers/replicationdestination_controller.go
controllers/utils/cleanup.go
controllers/utils/cleanup_test.go
controllers/utils/utils_suite_test.go
controllers/volumehandler/volumehandler.go
controllers/volumehandler/volumehandler_test.go

Provides a way for a user to label a snapshot with a `do-not-delete` label.  
If the label is present and equal to "true":
- Do not cleanup the snapshot in the cleanup cycle at the end of all mover's reconcile.  Remove the volsync cleanup label and also remove ownership so the snapshot will not be deleted when the ReplicationDestination is deleted.
- At the beginning of replication destination Reconcile, also check and remove the cleanup label and ownership.
Even though this is really intended for ReplicationDestination only, technically the cleanup cycle will happen in movers for ReplicationSource too - so that cleanup would do the same thing if someone happened to add the do-not-delete label to a …

Do not delete snap label

---

Dockerfile
Makefile
Procedures.md
controllers/mover/rclone/rclone_test.go
controllers/mover/restic/restic_test.go
controllers/mover/rsync/rsync_test.go
hack/run-in-kind.sh
mover-rclone/Dockerfile
mover-restic/Dockerfile
mover-syncthing/Dockerfile

This moves us to the standard golang 1.17 images in preparation to switch to 1.18
Depend on: openshift/release#28429

Switch to upstream golang 1.17

---

CHANGELOG.md
helm/volsync/Chart.yaml
kubectl-volsync/volsync.yaml

Updates a files with info about the 0.4.0 release
- Missed the version bump in the helm chart
- Updates the krew plugin manifest w/ the final version and sha hash
- Updates Changelog w/ final date/version

Metadata fixups for 0.4.0 release

---

.github/workflows/operator.yml
hack/setup-kind-cluster.sh

- Upgrades kind to 0.13 for 1.24 support
- Adds 1.24 to list of versions in CI matrix
- Bumps other minor kube versions to latest z
- Updates CSI hostpath driver to latest release
- Fixes issue where 1.18 was using wrong version of hostpath driver though this doesn't matter since we only test w/ 1.20+ at this point
- Kind version 0.13 is required for kube 1.24 support.

Add kube 1.24 to test matrix

---

controllers/replicationsource_test.go

Runs some replication source test with a manual trigger to avoid a timing issue where another test cycle could get started before the test has a chance to validate the results.
Fixes: https://github.com/backube/volsync/issues/213

Use manual trigger in test to avoid multiple syncs during test

---

CHANGELOG.md
Makefile
Procedures.md
helm/volsync/Chart.yaml
mover-rclone/Dockerfile
mover-restic/Dockerfile

- golangci-lint to 1.46.1
- helm to 3.8.2
- kuttl to 0.12.1
- Rclone upgraded to 1.58.1
- Restic upgraded to 0.13.1
Also updates the CHANGELOG and the changelog in the Helm chart

Update utility dependencies

---

Dockerfile
mover-rclone/Dockerfile
mover-restic/Dockerfile
mover-rsync/Dockerfile
mover-syncthing/Dockerfile

RHEL9 is GA. This switches our base containers to use ubi9 instead of ubi8.
It also cleans up the microdnf calls across the different containers.

Switch containers to ubi9

---

.github/workflows/operator.yml
Makefile

- Attempt to speed actions CI tests by breaking the unit tests into its own job
- Also upgrades the version of some of the actions

Parallelize CI by separating unit tests

---

.github/workflows/documentation.yml
docs/requirements.txt
docs/setup-env.sh

The sphinx-toolbox version had been pinned due to 2.18.0 not working.
Now that version 3 has been released, we can remove the pin.
This also fixes a problem w/ the `setup-env.sh` script where it would fail if not run from the `docs/` directory.

Unpin sphinx-toolbox

---

hack/setup-kind-cluster.sh

External snapshotter v6 was just released, and it removes the v1beta1 snapshot API. This is designed to correspond to kube 1.24+. This PR adjusts the kind deployment script accordingly.

Move kind to snapshotter v6 for 1.24+

---

.github/dependabot.yml
.github/workflows/documentation.yml
.github/workflows/operator.yml

- Enables dependabot to keep go.mod and GH actions up-to-date
- Switches the version specifier for actions to be SHA hashes instead of tags to improve security
- Increases the fetch-depth of the git checkout for the job that does code coverage to see if that improves the consistency of the coverage reports from codecov

Enable dependabot updates

---

go.mod
kubectl-volsync/cmd/relationship.go

~Upgrades gopkg.in/yaml.v3 to fix a dependabot security alert~
Really just switches the cli to use v3 of yaml. The v3 security alert was fixed in #237 

Switch relationship.go to yaml.v3

---

hack/run-minio.sh

- 9.0.5 is no longer in the bitnami repo
- This updates us to the latest version
We should probably establish some sort of strategy for ensuring the availability of the charts we use in CI

Update minio version

---

controllers/mover/events.go
controllers/volumehandler/volumehandler.go
controllers/volumehandler/volumehandler_test.go

For pvcFromSnapshot:
- attempt to use the restoreSize from the snapshot to determine size to create the PVC
- if restoreSize isn't available, attempt to use the status.capacity from the origin pvc
- fallback to using the requested storage size from origin pvc
For clone:
- attempt to use the status.capacity from the origin pvc
- fallback to using the requested storage size from origin pvc
- For snapshots, we had discussed making sure the snapshot is bound at the beginning of pvcFromSnapshot() - it turns out that  EnsurePVCFromSrc()  calls ensureSnapshot first and then pvcFromSnapshot (see https://github.com/backube/volsync/blob/main/controllers/volumehandler/volumehandler.go#L73-L78)  - and in fact …

Pvc storage size - clone & snapshot - use capacity if possible

---

bundle/manifests/volsync.clusterserviceversion.yaml
helm/volsync/Chart.yaml
version.mk

Updates the operator CSV metadata to 0.4.1
- Did not add an olm.SkipRange as we'll be publishing to the same acm-2.5 channel, so a .z update should automatically be applied within the channel.
- In version.mk I left the CHANNEL list to include `stable`.  We may need to make sure we remove stable once we publish `0.5.0`.  I.e. if we ever publish a `0.4.2` after `0.5.0` do we need to be careful not to publish `0.4.2` to the stable channel?
- Do any of these files need to be updated with the `0.4.1` version?
- CHANGELOG.md
- kubectl-volsync/volsync.yaml
- helm/volsync/Chart.yaml
Fixes https://github.com/backube/volsync/issues/258

Version operator to 0.4.1

---

controllers/mover/rsync/rsync_test.go

I haven't been able to recreate, but this seems the most likely cause (snap updated with cleanup label and perhaps not updated in the client cache before running the clean up test).
Fixes https://github.com/backube/volsync/issues/275

Make sure cached client has label update before cleanup test

---

controllers/mover/syncthing/mover.go
controllers/utils/affinity.go
controllers/utils/affinity_test.go
test-kuttl/e2e/syncthing-cluster-sync/10-connect-syncthings.yaml
test-kuttl/e2e/syncthing-cluster-sync/15-verify-all-connected.yaml
test-kuttl/e2e/syncthing-cluster-sync/20-populate-syncthing-1-data.yaml
test-kuttl/e2e/syncthing-cluster-sync/25-verify-data-synced.yaml
test-kuttl/e2e/syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect.yaml
test-kuttl/e2e/syncthing-cluster-sync/35-verify-all-are-connected.yaml

Adds the RWO affinity checking/setting code from #248 to the Syncthing mover
I have removed the affinity setting logic that take into account VolSync pods that are using a volume. I believe it was causing the pods to restart too frequently due to many (unnecessary) affinity changes.
This does mean we're not covered in a corner case where **multiple** RS objects replicate the same RWO volume w/ Direct.
Fixes #295
Fixes #300

Add RWO volume affinity to Syncthing

---

.github/workflows/stale.yml

Sets up the stale-bot action to close PRs that have become inactive. It does not do anything w/ issues.
- PRs marked stale after 60 days
- PRs closed after an additional 30 days (total 90 days inactivity)

Automatically close inactive PRs

---

.github/workflows/operator.yml
helm/volsync/Chart.yaml
helm/volsync/templates/deployment-controller.yaml
helm/volsync/values.yaml

- Adds Syncthing to the Helm chart so that its images can be customized like the other movers
- Updates the GH workflow to properly load the ST image under test instead of `:latest`

Add Syncthing to the Helm chart

---

.github/workflows/operator.yml

#307 changed the workflow for pushing container images, and broke it.
The container image names are stored as env variables, but the normal `${FOO}` syntax doesn't work for setting inputs to other workflows. It turns out that the `env` context also isn't available at that point in the workflow file, so I have resorted to just putting the value there.
From the action log, we see that the variable reference didn't get substituted. :disappointed: ... well, it did get substituted, it just needed to be done before the workflow call, not after.
```
Run docker load -i /tmp/image.tar
docker load -i /tmp/image.tar
docker inspect ${OPERATOR_IMAGE}
shell: /usr/bin/bash -e {0}
Loaded image: quay.io/backube/volsync:latest
"docker inspect" requires at least 1 argument. …
```

CI: Fix env substitution when calling push workflow

---

controllers/mover/rclone/rclone_test.go
controllers/mover/rclone/suite_test.go
controllers/mover/restic/restic_test.go
controllers/mover/restic/suite_test.go
controllers/mover/rsync/rsync_test.go
controllers/mover/rsync/suite_test.go
controllers/mover/syncthing/suite_test.go
controllers/mover/syncthing/syncthing_test.go
controllers/rclone_mover_test.go
controllers/replicationdestination_test.go
controllers/replicationsource_test.go
controllers/suite_test.go
controllers/utils/cleanup_test.go
controllers/utils/utils_suite_test.go
controllers/volumehandler/suite_test.go
controllers/volumehandler/volumehandler.go
controllers/volumehandler/volumehandler_test.go

- adds a helper function for unit tests to create an object and also wait for it to be loaded into the k8s client cache.  This is for unit tests that are using a reader cache and have objects that need to exist prior to the rest of the test running (creating a namespace for example)
- Moves some unit tests that aren't relying on controllers to use a direct k8s client  - the client that reads directly from the cache - to avoid these cache issues altogether
https://github.com/backube/volsync/issues/267
https://github.com/backube/volsync/issues/305

Unit test flakes client cache

---

CHANGELOG.md
helm/volsync/Chart.yaml
mover-rclone/Dockerfile

Updates the version of rclone embedded in the mover image

Update rclone to v1.59.0

---

go.mod
main.go

The operator pod's logs had been using a time format that was rather unreadable:
```
1.6593742610918622e+09	INFO	Starting EventSource	{"controller": "replicationsource", "controllerGroup": "volsync.backube", "controllerKind": "ReplicationSource", "source": "kind source: *v1.Secret"}
1.659374261091897e+09	INFO	Starting EventSource	{"controller": "replicationdestination", "controllerGroup": "volsync.backube", "controllerKind": "ReplicationDestination", "source": "kind source: *v1.Secret"}
1.6593742610919192e+09	INFO	Starting EventSource	{"controller": "replicationsource", "controllerGroup": "volsync.backube", "controllerKind": "ReplicationSource", "source": "kind source: *v1.Service"}
```
This fixes the timestamps:
```
2022-08-01T17:13:11.443Z	INFO	Starting …
```

controller: Fix log timestamp format

---

.ci-scripts/pre-commit.sh
.ci-scripts/yamlconfig.yaml
.github/dependabot.yml
.github/workflows/operator.yml
.gitignore
test-e2e/Pipfile
test-e2e/Pipfile.lock
test-e2e/README.md
test-e2e/ansible.cfg
test-e2e/inventory.yml
test-e2e/requirements.yml
test-e2e/roles/compare_pvc_data/tasks/main.yml
test-e2e/roles/create_namespace/handlers/main.yml
test-e2e/roles/create_namespace/tasks/main.yml
test-e2e/roles/create_rclone_secret/tasks/main.yml
test-e2e/roles/gather_cluster_info/tasks/main.yml
test-e2e/roles/get_minio_credentials/tasks/main.yml
test-e2e/roles/write_to_pvc/tasks/main.yml
test-e2e/run_tests_in_parallel.sh
test-e2e/test_simple_rclone.yml
test-e2e/test_simple_rsync.yml

Since we've been bumping against the limits of kuttl for some time, this is an exploration of moving the e2e tests into Ansible instead.
- This is an experiment... I'd like feedback from others.
- Does this look awful? Does it look impossible to write?
- Does it look any better than kuttl?
- *I happen to think this is really promising... the tests are largely straight-line, and roles give us the ability to re-use code.*
About the structure:
My intent is that each test would have a top-level `test_foo.xml` that is a playbook. That playbook would have the test, plus callouts into individual roles where there is re-usable code. A good example is the role "create_namespace". It creates a randomly named …

tests: Switch tests from kuttl to Ansible

---

test-e2e/roles/compare_pvc_data/meta/main.yml
test-e2e/roles/compare_pvc_data/tasks/main.yml
test-e2e/roles/compare_pvc_data/templates/pod.yml.j2
test-e2e/roles/write_to_pvc/meta/main.yml
test-e2e/roles/write_to_pvc/tasks/main.yml
test-e2e/roles/write_to_pvc/templates/pod.yml.j2
test-e2e/test_simple_rclone.yml
test-e2e/test_simple_rsync.yml

This turns the Pod descriptions for "write data" and "compare PVCs" roles into templates that get expanded differently based on the version of kube/openshift they are invoked against. This permits us to run the tests as non-uid0.

tests: Templatize Pods so they run as non-root on kube and OCP

---

test-e2e/README.md
test-e2e/roles/cli/tasks/main.yml
test-e2e/test_replication_sched_snap.yml
test-e2e/test_replication_sync_direct.yml

When I wrote the CLI role, I didn't consider that the role timeout wouldn't propagate to the actual CLI-calling task. This permits sending a parameter to the cli role that will be used to override the default task timeout when invoking the CLI executable

tests: Allow overriding the command timeout for cli commands

---

hack/setup-kind-cluster.sh

This removes the socat container before deploying the CSI hostpath driver.
The CSI hostpath driver exposes the `csi.sock` via TCP using a socat container. This is unnecessary for our usage--- it's there for testing the CSI driver.
It periodically causes problems for local kind clusters since it's pulled from docker.io and sometimes triggers throttling due to the number of pull requests coming from a given IP.

CI: Remove socat test pod from csi-hostpath in kind

---

test-e2e/roles/test_syncthing_cluster_sync/tasks/main.yml

We're seeing cases where the syncthing pods aren't being deleted within the timeframe allowed in the test. Manual testing indicates that the pods do eventually get deleted. This appears to be an issue of scheduling/deleting latency on the kube-side.
This increases the timeout during the test.

tests: Increase timeout waiting for syncthing pods to be deleted

---

controllers/mover/rclone/mover.go
controllers/mover/restic/mover.go
controllers/mover/rsync/mover.go
controllers/mover/syncthing/mover.go
controllers/utils/affinity.go
controllers/utils/affinity_test.go

Stops setting NodeName in the mover job spec and instead uses NodeSelector.  It seems that specifying NodeName directly bypasses the scheduler which means that if we have a PVC (like the restic cache pvc) that is in pending (because the storageclass has volumeBindingMode: `WaitForFirstConsumer`) - then the PVC will be stuck waiting for first consumer, and at the same time the mover pod is stuck waiting for the cache PVC to be Bound.  It seems using NodeSelector does go through the scheduler and everything starts as it should.
We are using the common node label `kubernetes.io/hostname` for the NodeSelector. …

Use nodeSelector rather than nodeName to not bypass scheduler

---

controllers/utils/sahandler.go
helm/volsync/templates/deployment-controller.yaml
helm/volsync/values.yaml

Backport 2 commits from #374 so that VolSync will run on dev builds of OpenShift 4.12
The downstream product doesn't use the Helm chart, but backporting that commit so that the upstream release is consistent w/ DS.
#374

Backport fixes for PSS

---

mover-restic/.gitignore
mover-restic/Dockerfile
mover-restic/README.md
mover-restic/patch-sources.sh

This adds a script that runs during the container build and removes references to the "optimized" sha256-simd library that was interfering w/ FIPS-compatible compilation
Fixes #389

restic: Patch restic to remove sha256-simd

---

mover-syncthing/entry.sh

This ensures we use the golang internal implementation so that we're compatible with the fips-enabled golang compiler.
Syncthing thankfully has built-in support for switching implementations, gated by an environment variable.
Fixes #394

syncthing: Disable use of minio's sha256-simd library

---

api/v1alpha1/common_types.go
bundle/manifests/volsync.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/mover/builder.go
controllers/mover/rclone/builder.go
controllers/mover/rclone/rclone_test.go
controllers/mover/restic/builder.go
controllers/mover/restic/restic_test.go
controllers/mover/rsync/builder.go
controllers/mover/rsync/rsync_test.go
controllers/mover/syncthing/builder.go
controllers/mover/syncthing/syncthing_test.go
controllers/replicationdestination_controller.go
controllers/replicationsource_controller.go
controllers/utils/namespace.go
controllers/utils/namespace_test.go
helm/volsync/templates/clusterrole-manager.yaml

- Looks for annotation `volsync.backube/privileged-movers: true` on the namespace the ReplicationSource/Destination is running in to determine if the user is allowing privileged movers
- I put the annotation constant itself in api/v1alpha1 - in case any users want to access it - is there a better location for it?
- Currently this change is only looking at the namespace annotation - Anything else we should be looking for such as the kube version or the namespace labeling itself? 
Fixes https://github.com/backube/volsync/issues/365

Check for mover privilege annotation on ns and pass to movers

---

.github/workflows/operator.yml
hack/setup-kind-cluster.sh

- Upgrades kind to 0.15
- Adds Kubernetes 1.25.0 to the test matrix
- Updates older kube minor versions to latest image supported by kind

CI: Add kube 1.25 to test matrix + kind 0.15

---

controllers/mover/rsync/mover.go
controllers/utils/utils.go
controllers/utils/utils_test.go

In cases where the source PVC accessModes only supports ReadOnlyMany (ROX), mount the pvc as read-only in the ReplicationSource mover job.
- Not doing this for other PVCs as I have encountered permission errors when trying to access the volume mounted as read-only.  So far testing with CephFS and ROX pvcs it does not have issues when mounting read-only.
- Attempts to avoid changing for most current scenarios by mounting read-only only for replicationSource (where we do not need to write to the PVC) and only when the source PVC access modes only allow ROX.
- This change right now is confined to rsync - we could potentially attempt to do a similar change …

rsync src mover - mount PVC as readOnly for ROX

---

.ci-scripts/yamlconfig.yaml
bundle/manifests/volsync.backube_replicationdestinations.yaml
bundle/manifests/volsync.backube_replicationsources.yaml
bundle/manifests/volsync.clusterserviceversion.yaml
config/crd/bases/volsync.backube_replicationdestinations.yaml
config/crd/bases/volsync.backube_replicationsources.yaml
config/rbac/role.yaml
controllers/platform/properties.go
controllers/platform/properties_test.go
controllers/platform/scc-crd.yml
controllers/platform/suite_test.go
go.mod
go.sum
helm/volsync/crds/volsync.backube_replicationdestinations.yaml
helm/volsync/crds/volsync.backube_replicationsources.yaml
helm/volsync/templates/clusterrole-manager.yaml

Adds the "platform" package that probes the cluster to determine properties of the cluster. This is necessary for #363 so that the movers can adjust their Pod manifests properly.
Right now, all it does is detect whether it's OpenShift and whether the "restricted-v2" SCC is available on the cluster. These checks parallel what we had to do w/ the e2e test manifests to support both kube and OCP.
Detection of OpenShift is done by the presence of any SCC objects, and restricted-v2 is by checking for it specifically.
- Adds RBAC to the operator so that it can read SCCs
- #363
- #366

Add package to detect platform properties

---

bundle/manifests/volsync.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/utils/affinity.go
controllers/utils/affinity_test.go
helm/volsync/templates/clusterrole-manager.yaml

- lookup label from the node itself to avoid issues where the kubernetes.io/hostname label on the node does not match the node name
- fixes the scenario where the nodeSelector would be set incorrectly by assuming the `kubernetes.io/hostname` label on a node would match the node name
- I put the //+kubebuilder annotations for rbac in the affinity.go file itself - I noticed @JohnStrunk did something similar with the platform/properties.go and had never thought of doing that before - Added the pod ones there as well just to be complete - these could be moved to the controller code if that is preferable. …

Lookup node in affinity getter to set nodeSelector

---

mover-rsync/source.sh

Rsync if provided with an IPv6 address needs to use the address in the format [ipv6addr].  This is a URL format.
In the mover script, attempt to detect if the destination address is an ipv6 address and wrap with [] only if it does not already contain [].  This hopefully avoids issues with urls that are already formatted correctly.
- Crude ipv6 check - checking that there are enough stanzas with : (or :: is found)
- Also avoids wrapping with [] if the address already contains [] - potentially could happen with a url address that embeds an ipv6 address?
https://github.com/backube/volsync/issues/402

detect ipv6 dest addr and pass with [] to rsync

---

controllers/mover/rclone/mover.go
controllers/mover/rclone/rclone_test.go
mover-rclone/active.sh

Instead of writing the "permissions.facl" file into the data volume and syncing, this mounts a tempdir and places the file there.
- Benefit: Doesn't modify the user's data volume
- Drawback: Requires 2 rclone calls (one for data, one for the permission file)
- #366
- #411

rclone: Don't write permission file into data volume

---

kubectl-volsync/volsync.yaml

Update krew plugin for 0.5.0 so it points to the 0.5.0 asset here:  https://github.com/backube/volsync/releases/download/v0.5.0/kubectl-volsync.tar.gz

update kubectl krew plugin for volsync to 0.5.0

---

CHANGELOG.md
bundle/manifests/volsync.clusterserviceversion.yaml
version.mk

Prepare for 0.5.1 release by updating version metadata
https://github.com/backube/volsync/issues/421

Prepare for 0.5.1 - update metadata

---

controllers/mover/restic/mover.go
controllers/mover/restic/restic_test.go
docs/usage/restic/index.rst

restic expects GAC to hold the path to a json file w/ the actual credentials, but we didn't have a method to actually mount the json file into the container. This change makes it possible to supply the json file **in the restic Secret** under the GAC key name. VolSync then takes the value and mounts that in the container and sets up an appropriate env var to point to it.
The usage of the GAC env var is not what is contained in the restic docs (a filename), instead, it's the actual file's contents.
Fixes #349

Allow passing in GOOGLE_APPLICATION_CREDENTIALS

---

CHANGELOG.md
bundle/manifests/volsync.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
helm/volsync/Chart.yaml
helm/volsync/templates/deployment-controller.yaml
test-e2e/Pipfile
test-e2e/Pipfile.lock

This also changes the repo from kubebuilder's mirror to the actual upstream repo. The change is because there seems to be a significant lag between the two.

Upgrade kube-rbac-proxy to v0.13.1

---

.ci-scripts/pre-commit.sh
CHANGELOG.md
Makefile
helm/volsync/Chart.yaml
helm/volsync/README.md
helm/volsync/templates/volsync.backube_replicationdestinations.yaml
helm/volsync/templates/volsync.backube_replicationsources.yaml
helm/volsync/values.yaml

Helm will only install CRDs if they are not present. It will not upgrade
or remove them. This change switches the CRDs to be managed as a part of
the templating mechanism so that they can be upgraded (and removed if
necessary).
This is a breaking change for Helm users as noted in the Changelog. In order for a chart upgrade to succeed, users will need to label/annotate the CRDs
Fixes #261

helm: Make chart manage VolSync CRDs

---

bundle/manifests/volsync.clusterserviceversion.yaml
version.mk

Creates version metadata for a 0.4.3 release
- Needed so we can inject e2e tests in the midstream (they won't run currently as the latest version is generated by freshmaker, thus a new version is required).
- We will also move the golang version to 1.19 in release-0.4, so might as well coincide this with 0.4.3.

version 0.4.3 in release-0.4

---

.github/workflows/operator.yml
custom-scorecard-tests/config.yaml
custom-scorecard-tests/generateE2ETestsConfig.sh
custom-scorecard-tests/scorecard/patches/e2e-tests.yaml

Adds github workflow job to check that generated files have been committed
- scorecard config.yaml (generated by make custom-scorecard-tests-generate-config)
- crd files (generated by make manifests)
- deepcopy .go files (generated by make generate)
- bundle metadata (generated by make bundle)
https://github.com/backube/volsync/issues/481

GH workflow check for generated files updated

---

test-e2e/run_tests_in_parallel.sh
test-e2e/test_rclone_priv.yml

When running tests for the privileged rclone mover, the uid of the files may not match due to how UIDs are handled on OpenShift. This skips verifying that uids match between src and dst volumes.

e2e: Don't compare uid for rclone w/ priv mover

---

test-e2e/roles/compare_pvc_data/templates/job.yml.j2
test-e2e/roles/pvc_has_data/tasks/main.yml
test-e2e/roles/pvc_has_data/templates/job.yml.j2
test-e2e/roles/write_to_pvc/tasks/main.yml
test-e2e/roles/write_to_pvc/templates/job.yml.j2
test-e2e/test_rclone_normal.yml
test-e2e/test_rclone_priv.yml

The rclone tests (privileged and unprivileged) were using the same s3 path, causing a race. This was only noticeable for the priv test because that one was preserving the UID of the files.
Also:
- Dumps logs from the "helper tools" roles pods.
- Backs out ignoring the mismatches of UIDs (#494)
Reverts #494

e2e: Fix Rclone privileged test

---

.github/workflows/operator.yml
Makefile
Procedures.md

- custom scorecard config generation was always using "latest" which doesn't actually match what we want in release branches - where we want to use the custom-scorecard-image tagged with "release-x.y". This attempts to use the correct tag on the custom scorecard image.

Fix auto gen chck for release branches

---

custom-scorecard-tests/config.yaml
custom-scorecard-tests/scorecard/patches/deploy-prereqs.yaml
custom-scorecard-tests/scorecard/patches/e2e-tests.yaml

- Updates custom scorecard config.yaml to use the custom-scorecard image for release-0.6.  Needed as the one in main (i.e. latest) will eventually diverge.

update cust scorecard config to use release-0.6 tags

---

.github/workflows/operator.yml
test-e2e/run_tests_in_parallel.sh

This makes the parallelism of the e2e test script more configurable. The following env vars can be defined:
- MAX_PARALLELISM: The max number of tests to run at once. Once those complete, another set of MAX will be run until all have been run
- BATCHES: Divide the total number of tests up into this many groups, and run one group at a time
When none of the above are set, the current behavior of running all tests at once is preserved.

tests: Add support for running e2e in batches

---

test-e2e/roles/test_syncthing_cluster_sync/tasks/kill_pods_by_label.yml

With the change to using multiple NS for the syncthing tests, we are deleting the ST pods one-by-one. This change switches to doing it synchronously to hopefully avoid an error where the 2nd delete was not finding the pod and failing.

e2e: Synchronously delete the Syncthing pods

---

.github/workflows/project-auto-add.yml

Adds a new GH workflow that is triggered when a new issue is created. This workflow automatically adds the issue to our new tracking project board.

CI: Add GH action to auto add new issues to project board

---

.github/workflows/operator.yml

We've been getting a lot of CI failures because the codecov server has been unable to get information from the GitHub API. It seems to be a known problem w/ rate limiting. Since it's been happening for an extended period, I'd like to not fail builds when coverage can't be uploaded.
This will mean that coverage stats may be out of date (or we don't get the PR comment), but it doesn't seem good to hold up a PR just for this.

CI: Don't fail if we can't upload coverage results

---

Dockerfile.volsync-custom-scorecard-tests

The custom scorecard build has a tendency to fail when installing dependenties over the network. This adds a retry script we use in other places to automatically retry a few times before failing.

tests: Add retries to scorecard build

---

mover-syncthing/.stignore
mover-syncthing/Dockerfile
mover-syncthing/entry.sh

Fixes: https://github.com/backube/volsync/issues/542
- Adds an .stignore file with lost+found in the syncthing Dockerfile
- Copies the .stignore file into the mounted data dir at the beginning of the mover script (will not overwrite a users' .stignore file if it already exists there)
https://github.com/backube/volsync/issues/542

syncthing: ignore lost+found

---

.github/workflows/operator.yml
hack/setup-kind-cluster.sh

- Adds 1.26 to the CI test matrix
- Upgrades kind to 0.17.0

CI: Add kube 1.26 to test matrix, update kind

---

.github/workflows/operator.yml
custom-scorecard-tests/config.yaml
custom-scorecard-tests/scorecard/patches/e2e-tests.yaml
test-e2e/roles/create_namespace/handlers/main.yml
test-e2e/roles/create_namespace/tasks/main.yml
test-e2e/test_namespace_role.yml

The namespace role was returning more than just the newly requested namespaces in the namespace list, causing test failures.
This reworks the namespace creation:
- Namespaces are now named `test-xxxx-n` where `xxxx` is a random integer that will be common for the namespace creation request, and `n` is an integer index for the namespace within the request: `0 ... num_namespaces-1`.
- The temporary variables used in the role are now prefixed to prevent leakage outside the role
- Determining the number to create no longer leaks the `num_namespaces` variable to the outside

e2e: Fix namespace role returning incorrect list of ns

---

hack/setup-kind-cluster.sh

Updates the external-snapshotter version to v6.2.1

tests: Update kind cluster to use external-snapshotter v6.2.1

---

test-e2e/roles/create_namespace/handlers/main.yml

Ignores 404 when trying to delete Namespaces. This happens w/ the namespace test role since it repeatedly tries to delete the same Namespaces. Most of the time, the k8s role does the right thing if the NS is already gone, but sometimes it fails w/ 404.
I can't reproduce the issue in kind, only in OCP. I suspect the issue is due to having multiple masters and the resulting eventual consistency.
Fixes #581

e2e: Make NS delete more robust

---

mover-rsync-tls/client.sh
mover-rsync-tls/server.sh

Periodically, the source seems to think the replication failed, while the destination registers success. This seems to be due to the destination shutting down before the rsync/stunnel connection properly terminates. This causes the source to believe the "shutdown" operation failed, and it restarts the replication.
This change adds a sleep on the destination to give the rsync & stunnel time to close the connection before terminating stunnel. It also adds a corresponding sleep on the source to ensure the source replication can't restart before the destination has terminated. Handling the race in this manner seems like a poor solution, but I'm at a loss for a better approach.
Fixes #580

rsync-tls: Give time for rsync to complete

---

bundle/manifests/volsync.clusterserviceversion.yaml
version.mk

- This is so we can publish to the ocp 4.12 catalog downstream the version being replaced needs to exist in the channel within the catalog, so we're removing it so we can "start again".
- Disadvantage is after publishing 0.5.2 it means users cannot bypass 0.5.2 and install 0.5.1 or 0.5.0 if they wanted.

Remove replaces 0.5.1 from csv

---

test-e2e/roles/test_syncthing_cluster_sync/tasks/kill_pods_by_label.yml
test-e2e/roles/test_syncthing_cluster_sync/tasks/main.yml

The task to kill the running syncthing pods would sometimes fail even though they had successfully killed the pod. This changes the delete to just use the pod label directly. That required getting rid of the wait in the delete operation. To substitute, I added a 30s sleep after all the delete operations. This will give the controller a chance to re-poll all the instances and update its view of connection state (in the CR's status field) so that the following tasks get the proper information.
I'm hoping this address some of the CI failures we've been seeing, particularly in openshift CI.

e2e: Try to make syncthing pod killing more robust

---

controllers/mover/rsynctls/logfilter.go
controllers/mover/rsynctls/logfilter_test.go
controllers/mover/rsynctls/mover.go
controllers/utils/podlogs.go
controllers/utils/podlogs_test.go

- rsync-tls logs a lot more detail than our other movers - when testing some scenarios where the destination could not be reached from the mover, the log saved ended up not having much useful error information as it would only catch the end of the log
- This is an attempt to catch some useful error strings
Update:
- Also default tail all logs from mover
- By default do not limit the lines we get from the mover pod
when getting logs - these will still be filtered & possibly
truncated before saving to the latestMoverStatus.
- Main motivation is rsync-tls is logging even more than I thought
previously so log lines were being missed.
#538

rsync-tls: add logfilter for failed mover job

---

api/v1alpha1/replicationdestination_types.go
api/v1alpha1/rsync_tls_types.go
api/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/volsync.backube_replicationdestinations.yaml
config/crd/bases/volsync.backube_replicationdestinations.yaml
controllers/mover/rsync/builder.go
controllers/mover/rsync/mover.go
controllers/mover/rsync/rsync_common.go
controllers/mover/rsync/rsync_test.go
controllers/mover/rsynctls/builder.go
controllers/mover/rsynctls/mover.go
controllers/mover/rsynctls/rsync_common.go
controllers/mover/rsynctls/rsync_test.go
helm/volsync/templates/volsync.backube_replicationdestinations.yaml

Fixes: https://github.com/backube/volsync/issues/596
- Adds a new field in the spec for rsync and rsyncTLS called "serviceAnnotations" to allow a user to set annotations on the service created by a replicationdestination.
Example usage:
```
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
name: rdest-tls-stuff
namespace: ttest
spec:
rsyncTLS:
serviceType: ClusterIP
serviceAnnotations:
"a": "b"
"service.beta.kubernetes.io/azure-load-balancer-internal: "true"
copyMethod: Snapshot
capacity: 2Gi
accessModes: [ReadWriteOnce]
```
- I used a pointer to map in the types
```
ServiceAnnotations *map[string]string …
```

svc annotations in spec (rsync & rsync-tls)

---

controllers/mover/rclone/mover.go
controllers/mover/rclone/rclone_test.go
controllers/mover/restic/mover.go
controllers/mover/restic/restic_test.go
controllers/mover/syncthing/mover.go
controllers/mover/syncthing/syncthing_test.go
controllers/utils/utils.go

If a user installs volsync via OLM, the cluster-wide proxy settings are injected as env vars. These env vars need to be set on the mover pods so that restic can use a custom transport.
I need to add tests
https://github.com/backube/volsync/issues/613
https://issues.redhat.com/browse/ACM-3216

Include cluster wide proxy env vars on restic mover

---

bundle/manifests/volsync.clusterserviceversion.yaml
version.mk

This reverts commit 395fbdb583a2ad61a5c13d1eb20678ef5b9fb86e.
Now that the `0.6.0` VolSync operator has been published, we're actually having issues building the VolSync 0.5.2 operator bundle downstream.  The issue seems to be that 0.6.0 is now in stable, but is now only getting published to ocp 4.10-4.12.  We think what's happening is for ocp 4.7, 4.8, 4.9 - the new build without replaces means it's having a hard time as we think the old versions are getting removed from the tree and perhaps the "stable" branch disappears (for the versions without a VolSync 0.6.0 in stable).
I've discussed with Gurney, and the solution that will probably work the best is to put back the "replaces" so builds can continue ok on everything except OCP 4.12, and then Gurney will …

Revert "Remove replaces 0.5.1 from csv"

---

Makefile

- Fixes issue with getting latest yq via our makefile
This is to fix the issue mentioned here: https://github.com/backube/volsync/pull/629#issuecomment-1438714226

GOFLAGS= to remove -mod=readonly when getting yq

---

bundle/manifests/volsync.clusterserviceversion.yaml
version.mk

Due to issues building downstream on OCP 4.12 the downstream builds needed to be split into 2 separate operator bundle builds, one for ocp <= 4.11 and ocp >= 4.12.
No code changes planned for v0.5.3, but making a new version so the downstream operator can be built again with 1 consistent bundle build for all OCP versions, and then freshmaker rebuilds with base img updates can also resume.

Make v0.5.3 version

---

bundle/manifests/volsync-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/volsync.clusterserviceversion.yaml
config/manager/manager.yaml
config/prometheus/monitor.yaml
config/rbac/auth_proxy_service.yaml

Fixes: https://github.com/backube/volsync/issues/678
Updates the pod selector in the volsync metrics service to be more unique by also checking for the label:
```
app.kubernetes.io/part-of: volsync
```
Also updates the deploy to use this label for its pods, and the ServiceMonitor example config/prometheus/monitor.yaml
Originally had planned to simply update the config/default/kustomization.yaml to set `commonLabels` which would automatically put the additional label on the deployment pods as well as the service (and their selectors).
However it turns out this breaks upgrades, as spec.selector is an immutable field on deployments, and when the spec.selector field is updated in the deployment within the …

volsync metrics svc in operator use unique label selector

---

CHANGELOG.md
helm/volsync/Chart.yaml

This is to update the CHANGELOG and helm chart.yaml (maybe I should cherry-pick into release-0.7 just to be consistent too).
We ended up having to ship the downstream 0.7.1 operator so I'm going to go ahead and do the 0.7.1 version in VolSync as well.
The operator needed to be shipped as we almost had that same downstream issue again where ocp 4.14 wasn't added to the support matrix - luckily the downstream staging catalog hasn't been seeded for 4.14 yet, so this means we need to get another v0.7.Z out there with ocp 4.14 in the matrix before this happens.

Updates for v0.7.1 release

---

CHANGELOG.md
api/v1alpha1/replicationsource_types.go
bundle/manifests/volsync.backube_replicationsources.yaml
config/crd/bases/volsync.backube_replicationsources.yaml
controllers/mover/restic/builder.go
controllers/mover/restic/logfilter.go
controllers/mover/restic/logfilter_test.go
controllers/mover/restic/mover.go
controllers/mover/restic/restic_test.go
docs/usage/restic/index.rst
helm/volsync/templates/volsync.backube_replicationsources.yaml
mover-restic/entry.sh

Allows a `restic unlock` to be run before backup in the next restic sync (backup).  Only applicable to ReplicationSource.
The field in the spec is: `spec.restic.unlock`.  Once this is set to a unique string value, this will not trigger a sync, but on the next scheduled sync `restic unlock` will be run prior to the backup.  Afterrwards the status (`status.restic.lastUnlocked` will be updated to the same string value from `spec.restic.unlock`.  No further unlocks will be run unless `spec.restic.unlock` is set to a different value from the one in the status.
- Removing `spec.restic.unlock` entirely is supported, and will remove `spec.status.lastUnocked` from the status after the next sync (and will also not …

Restic unlock

---

hack/setup-kind-cluster.sh

Updates the setup-kind-cluster.sh script to install the snapshot validation webhook (for kubernetes >= 1.24)
Fixes: https://github.com/backube/volsync/issues/632

kind setup - install validating webhook for snaps

---

controllers/replicationdestination_controller.go

maxConcurrentReconciles seems to be set 2x in the replicationdestination controller SetupWithManager() function. I believe the intention was to set it to 100 but it gets set back to 10:
Log excerpt (see "worker count"):
```
2023-04-25T21:02:01.041Z	INFO	Starting workers	{"controller": "replicationdestination", "controllerGroup": "volsync.backube", "controllerKind": "ReplicationDestination", "worker count": 10}
2023-04-25T21:02:01.143Z	INFO	Starting workers	{"controller": "replicationsource", "controllerGroup": "volsync.backube", "controllerKind": "ReplicationSource", "worker count": 100}
```

Remove setting maxconcurrentreconciles dup

---

bundle/manifests/volsync.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
helm/volsync/templates/deployment-controller.yaml

- Removes issues with TLS 1.2 supporting TLS cipher TLS_RSA_WITH_3DES_EDE_CBC_SHA
The TLS_RSA_WITH_3DES_EDE_CBC_SHA cipher is vulnerable to the SWEET32 attack as identified in CVE-2016-2183

Restrict rbac proxy to tls1.3 minimum

---

CHANGELOG.md
controllers/mover/restic/mover.go
controllers/mover/restic/restic_test.go

Restic - pass through env vars that start with `RCLONE_` from the restic secret to the mover job.
https://github.com/backube/volsync/issues/722

Restic rclone env vars

---

test-e2e/Pipfile
test-e2e/Pipfile.lock

Updates dependabot PR https://github.com/backube/volsync/pull/759 due to some additional dependencies needed for older python envs (custom-scorecard-tests use a ubi9 image with python 3.9).

bump ansible from 7.6.0 to 8.0.0 in /test-e2e

---

api/v1alpha1/common_types.go
api/v1alpha1/events.go
controllers/mover/events.go
controllers/mover/rsync/mover.go
controllers/mover/rsynctls/mover.go
controllers/volumehandler/volumehandler.go
controllers/volumepopulator_controller.go

Fixes: https://github.com/backube/volsync/issues/767

move event reason/action strings to api/v1alpha1 pkg

---

controllers/volumepopulator_controller_test.go

- updates to error out in Eventually() if we do get a flake to help debug if the issue still happens intermittently.
Try to address test flake that's occurred a couple times:
```
[FAILED] Timed out after 60.001s.
Expected
<bool>: false
to be true
In [JustBeforeEach] at: /home/runner/work/volsync/volsync/controllers/volumepopulator_controller_test.go:688 @ 06/19/23 18:54:52.177
------------------------------
•••••••••••••••••••••••••••••••••••••••••••••••
Summarizing 1 Failure:
[FAIL] VolumePopulator When a PVC is created that has a dataSourceRef with replicationdestination and a storageClassName When a storageclassname is specified in the pvc spec When the storageClass exists and latestImage snap is set on the RD [JustBeforeEach] When pvcPrime gets a PV …
```

Try to address volumepopulator test flake

---

Dockerfile
bundle/manifests/volsync.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
helm/volsync/templates/deployment-controller.yaml

- Restrict metrics to TLS 1.2 (was TLS 1.3).  TLS 1.3 has issues with FIPS envs in older OpenShift envs
- also USE CGO_ENABLED=1 when building.  This is really only required when using the openshift go toolset to build (for FIPS support) - but changing here so we're consistent with downstream builds.
See: https://access.redhat.com/security/vulnerabilities/RHSB-2023-001

Fips fixes

---

mover-restic/entry.sh

This moves the `sync` call at the end of the restic mover script so that it only happens after restore operations.
The sync exists to ensure data is flushed prior to creating a Snapshot. It is needed because we have no guarantee of sequencing between the node's `unmount` and the CSI snapshot operation that is triggered by our creation of the Snapshot object. Since the snapshot would only affect the destination volume (restore), it is only applicable there.
The unmount of volumes will cause their data to eventually get flushed, so when we don't care about sequencing, we don't need the explicit sync.
Fixes #788 
Related #792

restic: Make explicit sync only happen after restore

---

bundle/manifests/volsync.clusterserviceversion.yaml
version.mk

- Will be used to build with fips-or-die downstream
- Downstream will also include a CVE update for openssh in container images for CVE-2023-38408 that needs to be done in the midstream, cannot happen via freshmaker build.

Version 0.7.4

---

Makefile

- lock yq to v4.34.2 because the latest yq requires golang 1.20
- This was preventing unit tests from passing in PRs
this can be rolled back after we update to golang 1.20

Use YQ v4.34.2 because latest (v4.35.1) requires golang 1.20

---

Dockerfile
mover-syncthing/entry.sh

- Will leave cert.pem, key.pem in the syncthing config dir if they're already there
- This fixes issues with cert generation at startup in fips envs

Generate server certs at startup if first time

---

go.mod

Somehow, we ended up w/ a 2nd section of `require`s in the go.mod file. This merges them.

Collapse the 2 require sections in go.mod

---

Dockerfile.volsync-custom-scorecard-tests

Build the custom-scorecard-tests image using a ubi9/python-311 image instead of ubi9-minimal which packaged python 3.9 

Update custom-scorecard-tests img to python v3.11

---

Makefile

Trying to update our CI prow jobs to use a base image with python-311 here: https://github.com/openshift/release/pull/43732.  (this uses image registry.access.redhat.com/ubi9/python-311).
However this seems to start a virtual env automatically?  So when running "make test-e2e-install", it runs:
```
./.ci-scripts/retry.sh pip install --user --upgrade pipenv==2023.9.8
```
And this fails with an error like this:
```
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```
This change simply makes the --user flag a setting via `PIP_INSTALL_ARGS`.  This way in the prow job we can override to install without the `--user` flag by running:
```
make test-e2e-install PIP_INSTALL_ARGS=
```
**Is there anything that requires …

test-e2e-install target, make --user flag optional

---

CHANGELOG.md
Dockerfile

- Move back to rclone v1.63.1 as v1.64.0 has issues building on s390x
This reverts commit 9472fc4cd32b33ebdbf08b583dda6626d0cb5924.

Revert "Update rclone to v1.64.0"

---

test-e2e/Pipfile
test-e2e/Pipfile.lock

- Dependency is causing update issues and only needed for python 3.9 and earlier. Github actions are using python 3.10 for e2e tests and custom scorecard tests image is now using python 3.11

e2e tests - remove importlib-resources dependency

---

go.mod
go.sum
renovate.json5

- Disables renovate auto-update of openshift/api
- Syncs the module to the current commit on `release-4.14`

Disable automatic updates of openshift/api

---

mover-rsync-tls/client.sh
mover-rsync-tls/server.sh

Enabling TCP keepalives will hopefully allow VolSync to detect disconnections quicker in the presence of low-quality network connections
This is enabling keepalives and setting them to start after 3 minutes. Based on this, it should detect a broken connection w/in 15 minutes:
- TCP_KEEPCNT defaults to 9
- TCP_KEEPINTVL defaults to 75
180 + 9*75 = 855 sec = 14.25 min

Enable TCP-level keepalive for rsync-tls mover

---

mover-restic/entry.sh

Excludes lost+found from restic backups
fixes: https://github.com/backube/volsync/issues/1033

exclude lost+found for restic

---

.github/workflows/operator.yml
hack/setup-kind-cluster.sh

- Adds kube 1.29.0 to the GH actions test matrix
- Changes the default kind cluster to be 1.29.0

CI: Add kube 1.29 to test matrix

---

helm/volsync/Chart.yaml
helm/volsync/templates/deployment-controller.yaml
helm/volsync/values.yaml

It is already possible to define Pod annotations on the volsync controller Deployment. This PR makes it possible to set Pod labels as well.

feat: Add podLabels to Helm chart

---

api/v1alpha1/common_types.go
api/v1alpha1/events.go
controllers/errors/errors.go
controllers/errors/errors_suite_test.go
controllers/errors/errors_test.go
controllers/mover/rclone/mover.go
controllers/mover/rclone/rclone_test.go
controllers/mover/restic/mover.go
controllers/mover/restic/restic_test.go
controllers/mover/rsync/mover.go
controllers/mover/rsynctls/mover.go
controllers/mover/rsynctls/rsync_test.go
controllers/replicationsource_controller.go
controllers/utils/copy_trigger_annotations.go
controllers/utils/podlogs.go
controllers/volumehandler/volumehandler.go
custom-scorecard-tests/config.yaml
custom-scorecard-tests/scorecard/kustomization.yaml
custom-scorecard-tests/scorecard/patches/e2e-tests.yaml
main.go
test-e2e/test_restic_manual_normal_copy_trigger.yml

Allows copy-trigger annotations on the pvc to pause/trigger snapshots or clones in a sync
- latestMoverStatus is handled a little strangely - if we timeout waiting on someone to update the `copy-trigger` I will put the error and status in `latestMoverStatus`.  This was normally reserved for only errors during a job, but seemed like the best place to put this.  If we just return an error it'll end up in the conditions - but then will get overwritten as soon as we try to sync again with a syncing  status.  I think this is the case in general with errors (that are not job failures) in VolSync.

Copy trigger annotations

---

controllers/mover/rclone/mover.go
controllers/mover/rclone/rclone_test.go
controllers/mover/restic/mover.go
controllers/utils/utils.go
controllers/utils/utils_test.go
docs/usage/rclone/rclone-secret.rst

Rclone mover: Allows RCLONE_ env vars to be set in the rclone secret.
Closes: https://github.com/backube/volsync/issues/1097

Rclone env vars

---

docs/usage/index.rst
docs/usage/resourcerequirements.rst

docs for mover resource requests/limits

---

.github/workflows/operator.yml
api/v1alpha1/events.go
controllers/mover/syncthing/mover.go

It seems like we've been having a lot of intermittent CI failures. This switches from running a fixed number of "batches" to capping the maximum parallelism. The batch size was increasing as additional tests were added... By switching to parallelism limits, the number of batches will automatically increase as needed.

ci: Limit the amount of parallelism in e2e tests

---

renovate.json5

Looking at Renovate's dependency dashboard, we have a lot of potential updates that are pending due to the current limit on the number of outstanding PRs. This increases (effectively removes) the limit so we can see all the pending updates.

Increase number of PRs renovate can have open

---

mover-rsync-tls/server.sh

Add ipv6 checker in mover-rsync-tls script
(cherry picked from commit 483b169f2939781480e79c185c4306fad235b9f1)

[release-0.9] Cherry-pick: Merge pull request #1104 from winkrs/add-ipv6-checker

---

CHANGELOG.md
controllers/mover/restic/logfilter.go
controllers/mover/restic/logfilter_test.go
mover-restic/entry.sh

- Allows a restic restore to a non-existent path - will initialize the path if it doesn't exist (as is done in a backup).  This still means backups will fail if bad credentials are supplied
- Ignore lost+found on restic backup when checking for empty source volume
Want to fix in main and then cherry-pick into release-0.9 (to be included in v0.9.1).
https://github.com/backube/volsync/issues/1172
https://github.com/backube/volsync/issues/1181

Restic restore nonexist path, ignore lost+found on backup empty dir check

---

go.mod

Explicitly sets go 1.21.0 in go.mod and removes the "toolchain" statement that got automatically put there by a go mod tidy.
We don't want to force a go 1.22 toolchain at this point.  It looks like with go 1.21 it's encouraged to set an X.Y.Z version as you need an explicit release version for the toolchain stuff to work.  In this case go mod tidy added the x.y.z and also added a toolchain statement with the go version used (I assume?) because we picked up syncthing which itself had a go.mod with `go 1.21.0`.
So simply using `go 1.21.0` in our go.mod means we can now run go mod tidy and it won't add a "toolchain" directive to the file on us.
This is better explained here:  https://github.com/golang/go/issues/62278#issuecomment-1698829945
**Is there anything …

Set go 1.21.0, remove toolchain 1.22 statement

---

renovate.json5

Renovate was supposed to be grouping all the golang updates together, but this doesn't appear to be happening (#1214, #1119). This attempts to fix the regex match so that they end up as a single PR.

Fix grouping of renovate golang updates

---

Dockerfile
api/v1alpha1/common_types.go
controllers/mover/rclone/mover.go
controllers/mover/restic/mover.go
controllers/mover/rsync/mover.go
controllers/mover/rsynctls/mover.go
controllers/mover/syncthing/mover.go
controllers/mover/syncthing/syncthing_test.go
controllers/utils/utils.go
mover-rclone/active.sh
mover-restic/entry.sh
mover-rsync-tls/client.sh
mover-rsync-tls/server.sh
mover-rsync/destination.sh
mover-rsync/source.sh
mover-syncthing/entry.sh

Allows an annotation `volsync.backube/enable-debug-mover` on the replicationsource or replicationdestination which will run the mover job in debug mode.
This will require the user to exec into the mover pod where the script that would normally run is copied to /tmp.  At this point
the user can edit the script and run it themselves.
The mover pod will sleep indefinitely - user can however remove the file called `/tmp/exit-debug-if-removed` which will
cause the mover pod to exit.
- Decided on the `/tmp/exit-debug-if-removed` file as I didn't want to try to install a ps command - and this seems pretty easy (users could just kill the pod if they wish as well but this will retrigger another pod).  Deleting …

Mover debug mode

---

custom-scorecard-tests/config.yaml
custom-scorecard-tests/scorecard/patches/deploy-prereqs-stage0.yaml
custom-scorecard-tests/scorecard/patches/e2e-tests-stage1.yaml
custom-scorecard-tests/scorecard/patches/e2e-tests-stage2.yaml

Update generated config yamls for custom-scorescard-tests so they reference the release-0.10 label
Ran:
```
make custom-scorecard-tests-generate-config CUSTOM_SCORECARD_IMG_TAG=release-0.10
```

Update custom-scorecard-tests img tag release-0.10

---

custom-scorecard-tests/config.yaml
custom-scorecard-tests/scorecard/patches/e2e-tests-stage1.yaml
mover-rsync-tls/client.sh
test-e2e/roles/write_to_pvc/tasks/main.yml
test-e2e/roles/write_to_pvc/templates/job.yml.j2
test-e2e/test_rsync_tls_normal_manyfiles.yml

Fixes rsync-tls issue with argments too long when many files are in the root of the source PVC 
- Made a copy of all files into /tmp/filelist.txt and then pass that as `--files-from` arg to rsync
- Needed to add `-r` flag to rsync (this flag is normally implied by `-a`, but gets turned off by default when using `--files-from`)
- added e2e tests that create 21k files 
- used long names to reduce the number of files needed to create the issue. Hopefully this doesn't cause perf issues with the actual e2e tests in CI.  In my own env the sync does take a lot longer, but the compare pvc checks actually were surprisingly fast.
- Also added some files on the source with subdirs and files/dirs that start with . …

Rsync tls toomanyfiles

---

custom-scorecard-tests/config.yaml
custom-scorecard-tests/scorecard/patches/e2e-tests-stage1.yaml
mover-rsync-tls/client.sh
test-e2e/roles/write_to_pvc/tasks/main.yml
test-e2e/roles/write_to_pvc/templates/job.yml.j2
test-e2e/test_rsync_tls_normal_manyfiles.yml

Cherry pick of https://github.com/backube/volsync/pull/1291 to release-0.10

[release-0.10] Cherry pick rsynctls toomanyfiles

---

mover-rsync-tls/client.sh
test-e2e/test_rsync_tls_normal_manyfiles.yml

- affected files in the root of the pvc
- for acm-12338

fix rsync-tls copy files that start with '#'

---

renovate.json5

Prevents renovate from updating the renovate pre-commit hooks outside of the scheduled time.
See: https://docs.renovatebot.com/configuration-options/#updatenotscheduled
Hopefully after this update, it will only make changes on Mondays prior to 9am, then let the PR sit for the rest of the week.

Prevent renovate from repeatedly updating hooks PR

---

controllers/mover/restic/logfilter.go
controllers/mover/restic/logfilter_test.go
custom-scorecard-tests/config-downstream.yaml
custom-scorecard-tests/config.yaml
custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage1.yaml
mover-restic/entry.sh
test-e2e/roles/create_restic_secret/tasks/main.yml
test-e2e/test_restic_manual_normal_restore_emptyrepo.yml

Updates the ensure_initialized function in the restic mover script.
I came across this info in the restic docs:  https://restic.readthedocs.io/en/stable/075_scripting.html#check-if-a-repository-is-already-initialized
Essentially it recommends using `restic cat config` in order to determine if a repo has been initialized.
A few things:
- It looks like there are some new return codes that will maybe help us show a better error if we can't connect to the repo
- Ideally I'd like to remove the check for return code 1 and return an error here (looks like generally rc=10 should mean the repo doesn't exist, and at that point we could run restic init).  However in cases like minio, if the bucket does not exist, we still get rc=1....so I left the previous behaviour in …

update ensure_initialized in restic mover script

---

controllers/mover/rclone/mover.go
controllers/mover/restic/mover.go
controllers/mover/rsync/mover.go
controllers/mover/rsynctls/mover.go

It appears that the restic mover will suppress errors when `EnsurePVCFromSource` is called.  If the `ReplicationSource` has incorrect values (- in my case, I had forgotten the `spec.restic.copyMethod` field) - the resource will silently fail to re-reconcile.
None that I can immediately see.
This PR addresses the following [issue](https://github.com/backube/volsync/issues/1454)
(Aside from this hiccup caused by user error - thank you for the excellent controller!  It's exactly what I've been looking for and works great.)

restic mover should return error if unable to 'EnsurePVCFromSrc'

---

Dockerfile

UsePam no for sshd_config
e2e running on ubuntu 24.04 (not sure of exact cause) is having issues with sshd allowing root access which is required for rsync ssh.  Seems to be related to PAM.
Very strange and unsure of exact cause, but seems to be recreatable with kind running on an ubuntu 24.04 host.  Something in PAM is simply failing and not allowing root to login.

Rsync e2e usepam no

---

mover-rclone/active.sh
mover-restic/entry.sh
mover-rsync-tls/server.sh
mover-rsync/destination.sh
mover-rsync/source.sh

This PR fixes a bug I observed in a cluster where I had many rsync-tls privileged volsync jobs running against Longhorn volumes, and at least one was doing a large transfer. After a short time, the load average on the node with the large transfer destination mover would shoot really high (around 15), and the node started having problems at the kubelet level (pods failing to start with CreateContainerError was the easiest to observe condition)
Digging deeper, I saw that the other destination mover pods on that node (not related to the large transfer) were hanging at the ends of their transfers, when they should have been exiting and recycled by the operator.
Comparing the logs to the script showed that the only thing that could have been hanging was the …

Sync only the target filesystem at the end of mover tasks

---

helm/volsync/templates/deployment-controller.yaml
helm/volsync/values.yaml

Put default value for kube-rbac-proxy in helm values.yaml, will allow it to be overriden more easily if a user wants.

helm update - put kube-rbac-proxy img in values

---

custom-scorecard-tests/config-downstream.yaml
custom-scorecard-tests/config.yaml
custom-scorecard-tests/scorecard/bases/patches/deploy-prereqs-stage0.yaml
custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage1.yaml
custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage2.yaml
helm/volsync/Chart.yaml

- Update custom scorecard tests for release-0.12 now that we have a release-0.12 branch 
- Update charts.yaml with 0.12.0-rc.1 for upcoming pre-release

Update custom-scorecard-tests for release-0.12 and set version in charts.yml for upcoming pre-release rc.1

---

CHANGELOG.md
controllers/mover/rclone/mover.go
controllers/mover/rclone/rclone_test.go
controllers/mover/restic/mover.go
controllers/mover/restic/restic_test.go
controllers/mover/rsync/mover.go
controllers/mover/rsync/rsync_test.go
controllers/mover/rsynctls/mover.go
controllers/mover/rsynctls/rsync_test.go
controllers/mover/syncthing/mover.go
controllers/mover/syncthing/syncthing_test.go
controllers/utils/utils.go
controllers/utils/utils_test.go
custom-scorecard-tests/config-downstream.yaml
custom-scorecard-tests/config.yaml
custom-scorecard-tests/generateE2ETestsConfig.sh
custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage1.yaml
custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage2.yaml
helm/volsync/Chart.yaml
test-e2e/roles/test_syncthing_cluster_sync/tasks/main.yml
test-e2e/test_restic_manual_normal_longname.yml
test-e2e/test_rsync_tls_normal_longname.yml
test-e2e/test_simple_rsync_longname.yml
test-e2e/test_syncthing_cluster_sync_normal_longname.yml

- fixes name length limit for services/labels/jobs (63 chars)
- Tries to preserve existing names when limit isn't hit to avoid migration issues
- When names are too long, uses a crc32 hash of the cr name instead of cr name itself in the name
Fixes: https://github.com/backube/volsync/issues/1470

Resourcenamelimit 63chars

---

CHANGELOG.md
controllers/mover/rclone/mover.go
controllers/mover/rclone/rclone_test.go
controllers/mover/restic/mover.go
controllers/mover/restic/restic_test.go
controllers/mover/rsync/mover.go
controllers/mover/rsync/rsync_test.go
controllers/mover/rsynctls/mover.go
controllers/mover/rsynctls/rsync_test.go
controllers/mover/syncthing/mover.go
controllers/mover/syncthing/syncthing_test.go
controllers/utils/utils.go
controllers/utils/utils_test.go
custom-scorecard-tests/config-downstream.yaml
custom-scorecard-tests/config.yaml
custom-scorecard-tests/generateE2ETestsConfig.sh
custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage1.yaml
custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage2.yaml
helm/volsync/Chart.yaml
test-e2e/roles/test_syncthing_cluster_sync/tasks/main.yml
test-e2e/test_restic_manual_normal_longname.yml
test-e2e/test_rsync_tls_normal_longname.yml
test-e2e/test_simple_rsync_longname.yml
test-e2e/test_syncthing_cluster_sync_normal_longname.yml

Resourcenamelimit 63chars
(cherry picked from commit 9dc08b29d5b63fdb0843302303ac90552faafd5f)
https://github.com/backube/volsync/issues/1470

[release-0.12] Merge pull request #1519 from tesshuflower/resourcenamelimit_63chars

---

CHANGELOG.md
bundle/manifests/volsync.clusterserviceversion.yaml
config/manager/manager.yaml
controllers/utils/sahandler.go
controllers/utils/sahandler_test.go
controllers/utils/utils.go
helm/volsync/Chart.yaml
helm/volsync/templates/deployment-controller.yaml
main.go

When imagePullSecrets are set in the volsync helm charts, will add cli command arg --mover-image-pull-secrets to the volsync controller.
When mover-image-pull-secrets are set, when reconciling a `replicationsource` or `replicationdestination` service account, the secret(s) will be copied from the volsync controller namespace (normally `volsync-system`) to the mover namespace and added to the service account created by volsync.
- In the mover namespace, only 1 secret will be created for each original secret in the volsync-system namespace.  These will be named based on a common prefix "volsync-pull-" plus a crc32 hash of the original secret name.
- If there are multiple volsync CRs in the namespace, they …

Mover pull secrets

---

test-e2e/roles/gather_cluster_info/tasks/main.yml
test-e2e/test_multi_sync_snapshot_rclone.yml
test-e2e/test_restic_with_customca_configmap.yml
test-e2e/test_restic_with_customca_secret.yml
test-e2e/test_restic_with_previous.yml
test-e2e/test_restic_with_restoreasof.yml
test-e2e/test_restic_without_trigger.yml

- some e2e tests didn't seem to get updated with moverSecurityContext after moving to unprivileged by default
- Updates kube minor version check in gather_cluster_info (for EKS, which returns kube version like: "1.30+")

Update e2e tests for unprivileged

---

bundle/manifests/volsync.clusterserviceversion.yaml
config/manager/manager.yaml
hack/run-minio.sh
hack/setup-kind-cluster.sh
helm/volsync/templates/deployment-controller.yaml
test-e2e/test_multi_sync_snapshot_rsync.yml
test-e2e/test_replication_sched_snap.yml
test-e2e/test_replication_sync_direct.yml
test-e2e/test_simple_rsync.yml
test-e2e/test_simple_rsync_diskrsync.yml
test-e2e/test_simple_rsync_longname.yml
test-e2e/test_volumepopulator.yml

- Updates to set seccompProfile to RuntimeDefault for OpenShift (previously we didn't set for Openshift, but this was only an issue with OpenShift <= 4.11 which is no longer supported).
- Updates the setup-kind-cluster.sh to enforce restricted by default
- some updates to e2e tests that need to run privileged but didn't set the label on the ns to allow privileged pods
- updates minio to an updated chart version that sets seccompProfile by default to RuntimeDefault

Kind enforce restricted and seccomprofile ocp

---

CHANGELOG.md
controllers/mover/restic/mover.go
controllers/mover/restic/restic_test.go
test-e2e/test_restic_manual_normal.yml
test-e2e/test_restic_manual_normal_cleanup_pvcs.yml
test-e2e/test_restic_manual_normal_longname.yml

Fixes: https://github.com/backube/volsync/issues/1575
- Will check for old cache pvc (with the previous name) and remove it if it exists, and then create/reconcile a cache pvc with the new name
https://github.com/backube/volsync/issues/1575

fix restic cache pvc name collisions for src & dst

---

.github/workflows/release.yml
.krew.yaml
Procedures.md

- build for amd64 and arm64 (one kubectl-volsync-linux-ARCH.tar.gz for each)
- always attach the asset to the release (even pre-release) to help with testing mostly
- update krew publish to look for both arch .tar.gz files

Update release workflow to attach kubectl-volsync for multi-arch

---

.github/workflows/operator.yml

release-0.13 br has a check to make sure the custom scorecard tests are setup to use "release-0.13" tag instead of "latest"...but if we're ffwding main -> release-0.13 then this won't work.  

fix gen-files check for ffwd branch

---

Dockerfile.rhtap

- add back steps we had in the upstream so symbols are not stripped for rclone & restic (so we can verify crypto libs with nm)

Dockerfile.rhtap add back fix to not strip symbols

---

.github/workflows/operator.yml
custom-scorecard-tests/config-downstream.yaml
custom-scorecard-tests/config.yaml
custom-scorecard-tests/scorecard/bases/patches/deploy-prereqs-stage0.yaml
custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage1.yaml
custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage2.yaml

After stopping ffwding from main-> release-0.13, I forgot to update the custom-scorecard-tests to use point to a `release-0.13` version of the image.

update cust scorescard tests to use release-0.13

---

helm/volsync/templates/deployment-controller.yaml
helm/volsync/values.yaml

ACM would like to be able to configure resource requirements for all containers in deployments for when they are deployed via the addon controller.  This should work fine for our manager container as the resources are already exposed in the helm chart values.yaml, but this update adds a separate values entry for the kube-rbac-proxy resources.

configurable resources for kube-rbac-proxy in helm chart

---

.github/workflows/operator.yml
hack/setup-kind-cluster.sh

- update k8s test matrix to include v1.33
- Also remove testing on some older k8s versions to reduce churn (we're not supporting OCP 4.12, 4.13 anymore anyway).
- Change default version of k8s used in hack/setup-kind-cluster.sh to 1.33.1 (this is the default k8s used by kind v0.29.0).

update k8s test matrix w/ 1.33

---

api/v1alpha1/replicationdestination_types.go
api/v1alpha1/replicationsource_types.go
bundle/manifests/volsync.backube_replicationdestinations.yaml
bundle/manifests/volsync.backube_replicationsources.yaml
bundle/manifests/volsync.clusterserviceversion.yaml
config/crd/bases/volsync.backube_replicationdestinations.yaml
config/crd/bases/volsync.backube_replicationsources.yaml
docs/usage/rsync/index.rst
helm/volsync/templates/volsync.backube_replicationdestinations.yaml
helm/volsync/templates/volsync.backube_replicationsources.yaml

for ReplicationSource & ReplicationDestination, .spec.rsync.path is a field that is ignored by the movers.  Update the docs and api to indicate that this field is unused.
https://github.com/backube/volsync/issues/1720

update docs/api to indicate that spec.rsync.path is not used

---

hack/run-minio.sh
mover-restic/entry.sh
test-e2e/test_restic_manual_normal_restore_emptyrepo.yml

- fixes a specific case where the previous 10 second timeout was not sufficient, so it is increased to 60 seconds
- to avoid applying the 60-second timeout to other cases, the restic-e2e bucket is created beforehand
- the test `test_restic_manual_normal_restore_emptyrepo` runs on an undefined bucket, so the number of retries is increased by 60 to prevent potential failures caused by this change
https://github.com/backube/volsync/issues/1710

Increase timeout on restic cat config

---

CHANGELOG.md
helm/volsync/Chart.yaml
mover-rclone/active.sh

RCLONE_ env vars are already passed into the running mover pod, as per documentation here: https://volsync.readthedocs.io/en/stable/usage/rclone/rclone-secret.html#using-rclone-environment-variables-in-rclone-secret
We previously hardcoded `--checksum`, -`-stats`, and `--transfers` flags when running sync and copy commands.
Now update to use RCLONE_ env vars, but set them to our existing defaults if they are not set by the user in the rclone config secret.  This enables users to override those settings if they wish.
Example from testing with logs:
```
2025/09/17 16:15:10 DEBUG : Setting --stats "20s" from environment variable RCLONE_STATS="20s"
2025/09/17 16:15:10 DEBUG : Setting --transfers "10" from environment variable RCLONE_TRANSFERS="10"
2025/09/17 …
```

1763 rclone transfers,  checksum flags

---

helm/volsync/Chart.yaml

commit to save the updated Chart.yaml for v0.13.1 in the release-0.13 branch (this is the Chart.yaml I've used for publishing the v0.13.1 helm charts) - I had forgotten to do this before we made our official v0.13.1 cutoff.

release-0.13 update chart.yaml for v0.13.1
